### ISSUE TITLE
Support LaTeX output as well as HTML

### ISSUE THREAD

**Issue by benjaminrich** [benjaminrich/table1#1]

**Comment by tdienlin** [comment]
That'd be so great! I've stumbled upon your great package and I'd really like to use it in rmd to export 
pdfs using papaja, which leads to nice manuscripts in APA style. Currently, if I see it correctly I can use your package only in my Online Supplementary Material, where I provide htmls. That's of course something, but if I could use it in the regular manuscript, that'd be even better. Thanks for the great work!

**Comment by benjaminrich** [comment]
A couple of people have used the `rvest::html_table()` function to parse the HTML output of `table1` back into R, which can then be converted to LaTeX using other packages, but I find this to be somewhat of a kludgy solution.

**Comment by kmace** [comment]
This would be an amazing feature. +1

**Comment by fshaikh4** [comment]
> A couple of people have used the `rvest::html_table()` function to parse the HTML output of `table1` back into R, which can then be converted to LaTeX using other packages, but I find this to be somewhat of a kludgy solution.

would you be able to provide more information on how to do this? would love to figure this out to have some sort of LaTeX PDF report with these tables (via RMarkdown).

**Comment by ck2136** [comment]
Just wanted to thank the author @benjaminrich as well as people trying the `rvest::html_table()` solution. I haven't tried it myself but I'll report back if it's doable. I'm compiling my dissertation right now with .Rnw and would love to be able to get output that would require minimal manipulation.

**Comment by benjaminrich** [comment]
The idea of using `rvest::read_html()` was proposed by @mtkent1 in https://github.com/benjaminrich/table1/issues/17#issuecomment-517298732.

**Comment by benjaminrich** [comment]
In the newly released version 1.4, it is now possible! LaTeX can be generated via `kableExtra` using the `t1kable()` function, or via `flextable` using the `t1flex()` function.
