### ISSUE TITLE
Suggestion:formatting control

### ISSUE THREAD

**Issue by hdeng88** [benjaminrich/table1#10]
I really enjoy your logic of creating an extra data-step to label the data.

I would suggest a formatting control function to go a little further. 

A lot of features of analyses are usually done in a priori fashion.  For example, I may want some variables output as mean(SD), some are median (Q1,Q3). And also I want to assign different digits for them, adding the labels, and assign a statistical test.

I will suggest a format_table1 function to wrap it up in the dataset, just like the label command.

format_table1(var = c("age","BMI"),sum = mean_sd, digits = c(1,2), test = c("ttest","wilcox"),smd = T)
format_table1(var = c("group, race"),sum = factor, digits = c(1,1), test = c("chi","fisher"),smd = F)

and then table1(...)

This will be very helpful if it is workable.

**Comment by rpkyle** [comment]
Not sure, but perhaps Hao is referring to the standardized mean difference -- I think this is a relevant reference:

Flury BK, Riedwyl H. Standard distance in univariate and multivariate analysis. The American Statistician. 1986;40:249–251.

SMDs are estimable in the tableone package using the smd argument, as described here:

https://cran.r-project.org/web/packages/tableone/vignettes/introduction.html

**Comment by hdeng88** [comment]
Yes, I was referring to Standarized mean difference. There is a trend for
academic journals requesting such treatment effect measures.

**Comment by benjaminrich** [comment]
Thanks @rpkyle. 

Like I said, this isn't something I am planning to implement. However, there is a hack to add a p-value column to the table (or other result like SMD, but only one column can be added this way). It has been in the vignettes since version 1.1.
