### ISSUE TITLE
Is extra row always on the right?

### ISSUE THREAD

**Issue by maozhy3** [benjaminrich/table1#106]
Hi,
I noticed that the extra.col is always on the right, and I wonder if there is any way to plug extra.col into two stratification? For example, i made such a table using photoshop xd
![image](https://user-images.githubusercontent.com/46839266/229303760-22774c59-3d9f-47f9-9fa0-587fe1d8c611.png)

And also there is a bug, when i have two extra.col , the upper line is missing.

![image](https://user-images.githubusercontent.com/46839266/229303815-631c91d9-8702-4790-8b36-9b2867b85024.png)

the code i used are as follow

 `
  pvalue1 <- function(xx, ...) {
    x<-list(xx[[1]],xx[[2]])
    y <- unlist(x)
    g <- factor(rep(1:length(x), times=sapply(x, length)))
    if (is.numeric(y)) {
      p <- t.test(y ~ g)$p.value
    } else {
      p <- chisq.test(table(y, g))$p.value
    }
    c("", sub("<", "&lt;", format.pval(p, digits=3, eps=0.001)))
  }
  
  
  pvalue2 <- function(xx, ...) {
    x<-list(xx[[3]],xx[[4]])
    y <- unlist(x)
    g <- factor(rep(1:length(x), times=sapply(x, length)))
    if (is.numeric(y)) {
      p <- t.test(y ~ g)$p.value
    } else {
      # For categorical variables, perform a chi-squared test of independence
      p <- chisq.test(table(y, g))$p.value
    }
    c("", sub("<", "&lt;", format.pval(p, digits=3, eps=0.001)))
  }
  table1(~ AD8outcome + age + education | residence*gender,data=data,overall=F,
         extra.col=list(`P-value1`=pvalue1, `P-value2`=pvalue2))

`

**Comment by benjaminrich** [comment]
The way to do this should have been using `extra.col.pos=c(3, 6)`, but unfortunately this is not playing nice with nested stratification (grouped columns). I am working on a fix, so stay tuned.

**Comment by benjaminrich** [comment]
A fix has been pushed. If you are able to install from GitHub you can try it out (otherwise you will have to wait until the next release). Here is a small example showing how it works:

```r
set.seed(123)
n <- 100
dat <- data.frame(
    A = rnorm(n),
    B = sample(c("X", "Y"), n, replace=T),
    C = sample(c("V", "W"), n, replace=T))

table1(~ A | B*C, data=dat, overall=F,
    extra.col=list(`P-value1`=pvalue1, `P-value2`=pvalue2), extra.col.pos=c(3, 6))
```

![image](https://user-images.githubusercontent.com/17572252/233907650-eb5c4315-cd4d-41ba-b725-c6e90c818936.png)
