### ISSUE TITLE
How to calculate row percentages instead of column percentages?

### ISSUE THREAD

**Issue by hdeng88** [benjaminrich/table1#13]
How to calculate row percentages instead of column percentages?

**Comment by hdeng88** [comment]
of course. 

for example, we use dimonds data-set
-----------
diamonds %>%  as.data.frame() ->aaa
table1(~cut|color,aaa)
-----------

The output is about for each color category, what is the percentage for each cut. That's great for cohort study. But sometimes we expect the opposite for case-control studies: for each cut category, what is the percentage for each color, while keeping color as the columns.

And how can I add statistical tests into the table? like a t-test or Chi-square test?

**Comment by benjaminrich** [comment]
There's no way to do that currently. Can you provide an actual example of what you want from a case-control study instead of the diamonds? Why is it important for case-control studies to have the row percentages?

There is a hack to add a p-value column to the table. It has been in the vignettes since version 1.1.

**Comment by hdeng88** [comment]
Thanks!

In some outcome research using medical administrative data, despite it was
defined as "case-control", clinical researchers often want to see the
"cohort like" relationship.

That is to say, for instance. assuming out study outcome is readmission in
30 days or not. We are running this study in a case-control framework.
However when it comes to the treatment options (A,B,C,D), physicians tend
to like more straight-forward way to look at the relationship, that is how
much percentage of patient who received A will have readmission? not how
much percentage of readmission patients used drug A.

Does that make sense to you?

I am trying to use your package as my go to package for tableone making
therefore this function is quite important to me.

Hao

**Comment by benjaminrich** [comment]
Yes, it makes sense. Like I said, this can't be done in the current framework. But, I can offer you this solution, which will only work for a single row variable (like treatment), and with no "overall" column:

```r
table.with.row.percentages <- function(formula, data) {
    formula[[2]][[1]] <- quote(`+`)
    m1 <- model.frame(formula, data=data, na.action=na.pass)
    lab <- table1::label(m1[[1]])
    if (is.null(lab)) lab <- names(m1)[1]

    t1 <- table(m1[[1]], m1[[2]])
    t2 <- margin.table(t1, 2)
    t3 <- prop.table(t1, 1)

    tab <- paste0(t1, " (", formatC(100*t3, format="f", digits=1), "%)")
    attributes(tab) <- attributes(t1)
    dimnames(tab)[[2]] <- paste0(dimnames(tab)[[2]], "<br/>(n=", t2, ")")

    tab <- rbind(rep("", ncol(tab)), tab)
    dimnames(tab)[[1]][1] <- lab

    x <- paste0(
        '<table>\n<thead>\n',
        table.rows(colnames(tab), th=T),
        '</thead>\n<tbody>\n',
        table.rows(tab),
        '</tbody>\n</table>\n')

    structure(x, class=c("table1", "html", "character"), html=TRUE)
}

# Example:
data <- expand.grid(status=c("Case", "Control"), treatment=LETTERS[1:4])
data <- data[sample(1:nrow(data), 300, replace=T),]
table.with.row.percentages(~ treatment | status, data=data)
```

Let me know what you think.

**Comment by MdAhsanulHimel** [comment]
> Yes, it makes sense. Like I said, this can't be done in the current framework. But, I can offer you this solution, which will only work for a single row variable (like treatment), and with no "overall" column:
> 
> ```r
> table.with.row.percentages <- function(formula, data) {
>     formula[[2]][[1]] <- quote(`+`)
>     m1 <- model.frame(formula, data=data, na.action=na.pass)
>     lab <- table1::label(m1[[1]])
>     if (is.null(lab)) lab <- names(m1)[1]
> 
>     t1 <- table(m1[[1]], m1[[2]])
>     t2 <- margin.table(t1, 2)
>     t3 <- prop.table(t1, 1)
> 
>     tab <- paste0(t1, " (", formatC(100*t3, format="f", digits=1), "%)")
>     attributes(tab) <- attributes(t1)
>     dimnames(tab)[[2]] <- paste0(dimnames(tab)[[2]], "<br/>(n=", t2, ")")
> 
>     tab <- rbind(rep("", ncol(tab)), tab)
>     dimnames(tab)[[1]][1] <- lab
> 
>     x <- paste0(
>         '<table>\n<thead>\n',
>         table.rows(colnames(tab), th=T),
>         '</thead>\n<tbody>\n',
>         table.rows(tab),
>         '</tbody>\n</table>\n')
> 
>     structure(x, class=c("table1", "html", "character"), html=TRUE)
> }
> 
> # Example:
> data <- expand.grid(status=c("Case", "Control"), treatment=LETTERS[1:4])
> data <- data[sample(1:nrow(data), 300, replace=T),]
> table.with.row.percentages(~ treatment | status, data=data)
> ```
> 
> Let me know what you think.

Thank you. It works for me. You are a savior.
