### ISSUE TITLE
na.rm = TRUE

### ISSUE THREAD

**Issue by davidhen** [benjaminrich/table1#18]
Is there any way of suppressing the default setting of including missing values as their own category in continuous variables? I have a dataframe with extra rows showing year of death (which I want to count), but the age value is coded as NA. Ideally I'd like the mean/median of age with na.rm=TRUE. I can't seem to figure it out with the abbreviated codes

**Comment by benjaminrich** [comment]
If I understand you correctly, you just want to suppress the row in the table that shows the count and percentage of missing values? If that's the case, you can try setting `render.missing=NULL`. Please use the current GitHub version to test.

**Comment by davidhen** [comment]
Yes, that is correct. Unfortunately I am using R in a secure environment so only get CRAN updates once a month. Am currently using version 1.1
I've tried `render.missing = NULL` in various guises with no joy.

**Comment by benjaminrich** [comment]
OK. Then try this:

```r
table1(..., render.missing=function(x, ...) character(0))
```

**Comment by davidhen** [comment]
Sorted! Thanks very much.

**Comment by benjaminrich** [comment]
Great!
