### ISSUE TITLE
Export to Word

### ISSUE THREAD

**Issue by smuyengwa79** [benjaminrich/table1#19]
Is there a way of exporting these tables to MSWord from Rmarkdown

**Comment by awcm0n** [comment]
I realize once can simply copy the html table from RStudio into a Word document, but I'd still like to be able to knit from RMarkdown to a Word document (the reason is that I rely on flextable a lot; the copy-paste method destroys the formatting of flextable tables but knitting to Word works).

**Comment by benjaminrich** [comment]
No, it's not possible at this time. Though of course it would be nice to have this ability, there are technical reasons why this is challenging. I am thinking about ways to add this functionality, but I'm not sure if or when I might be able to implement it.
