### ISSUE TITLE
Only outputs to image in RStudio

### ISSUE THREAD

**Issue by swood-ecology** [benjaminrich/table1#23]
When executing ```table1(...)``` in RStudio, the output pops up in the Viewer tab as an image, and exports as an image when you copy and paste. Is there a way to export as html?

**Comment by benjaminrich** [comment]
It depends what you mean by "export as html". The Viewer tab in RStudio is like a web browser. The table may look like an image, but it is not in fact an image, it's an HTML table. If you copy and paste from the Viewer into an MS Word document, you get a proper (editable) table, not an image. You have to make sure to select the whole table though (it's easiest to start from the bottom right). 

Another thing you can do is to "knit" the document (Ctrl+Shift+K in RStudio). This results in an HTML file that you can open in a web browser.

If what you want is the HTML tags as text, you can do that too, by saving the output to a variable. Take this small example from the vignette:

```r
library(table1)
library(boot)

melanoma2 <- melanoma

melanoma2$status <- 
  factor(melanoma2$status, 
         levels=c(2,1,3),
         labels=c("Alive", # Reference
                  "Melanoma death", 
                  "Non-melanoma death"))

txt <- table1(~ factor(sex) + age + factor(ulcer) + thickness | status, data=melanoma2)

print(txt)               # Renders in the Viewer tab
print(txt, browse=FALSE) # Outputs HTML tags to Console
cat(txt)                 # Outputs HTML tags to Console
as.character(txt)        # Converts to a character (and outputs to console)
```

**Comment by benjaminrich** [comment]
Closing this issue if you have no further comments.
