### ISSUE TITLE
Add option for standard error 

### ISSUE THREAD

**Issue by rohanshad** [benjaminrich/table1#25]
Need a way to plug in standard error instead of standard deviation

**Comment by benjaminrich** [comment]
By standard error, I assume you mean standard error of the mean. If you really need this, it can be done with a custom render function:

```r
render.cont <- function(x, ...) {
  s <- stats.default(x)
  s$SEM <- s$SD/sqrt(s$N)
  with(stats.apply.rounding(s), sprintf("%s (%s)", MEAN, SEM))
}
```
