### ISSUE TITLE
How to round to 2 decimals for continuous variable?

### ISSUE THREAD

**Issue by caiyi1993** [benjaminrich/table1#27]
Thanks for your package!

I am a noob to Rstudio from China. For completing my medical manuscript, I am learning to use your package to create table 1. However, I notice that the parameter of "digits" could only create a certain number of **signiﬁcant digits**(which is 3 in default set I know), like the figure below.

![image](https://user-images.githubusercontent.com/23131986/78353504-bfd6c600-75dc-11ea-881a-81b890b06949.png)
This is the corresponding code chunk:
`table1(~ L1Fovea_A+L1ParaFovea_A
       | AHIgroup3,data=osasel,render.continuous=c(.="Mean ± SD (Min, Max)"))`

If I want to have fixed decimal digits in continuous variables like the figure below, what should I do?
![image](https://user-images.githubusercontent.com/23131986/78354007-a5e9b300-75dd-11ea-9399-15223925a3d1.png)

I had read the pdf of Package ‘table1’ and still get no idea. I can only set the digits parameter to 4 or 5, and copy the table to excel to modify the decimal manually, which is really annoying.
Thanks!

**Comment by caiyi1993** [comment]
Oh! Sorry for the grammatical mistake...

**Comment by caiyi1993** [comment]
I learned "function()" tonight. This is the only way I can imagine to solve the problem: 
```
my.render.cont2 <- function(x) {
  with(stats.default(x), sprintf("%s &plusmn; %s (%s, %s)",round_pad(MEAN,2),round_pad(SD,2),MIN,MAX))
       }
            
table1(~ L1Fovea_A+L1ParaFovea_A
| AHIgroup3,data=osasel,render.continuous=my.render.cont2)
```
This is the output of the code chunk mentioned: 
![image](https://user-images.githubusercontent.com/23131986/78381787-71d7b780-7608-11ea-8e19-dd6ea48c08b2.png)

Sorry for the noob question. 
Am I doing right?
Do you have any better suggestions?

**Comment by benjaminrich** [comment]
Yes, I think you found the best solution.

**Comment by caiyi1993** [comment]
Thank you for helping me! :)
