### ISSUE TITLE
Gating error precision on the precision of the primary value

### ISSUE THREAD

**Issue by carbocation** [benjaminrich/table1#28]
Example:
```R
library(table1)
d <- data.frame(Height=c(rep(141.7, 100), rep(201.8, 100)))
table1(~., data=d)
```

With this example, I get:

  | Overall(n=200)
-- | --
Height |  
Mean (SD) | 172 (30.1)
Median [Min, Max] | 172 [142, 202]

Raw values in R:
```sh
> mean(d$Height)
1] 171.75

> sd(d$Height)
[1] 30.12541
```

The precision of the estimate of the mean is to the 1's position (3 sig figs). What is undesirable here is that the precision of the standard deviation is taken to the decimal position. While 30.1 is indeed 3 sig figs for that number taken in the abstract, I am surprised to see precision beyond the decimal that is 3 sig figs for the main value (here, the mean, which is 172). If the mean is rounded to the 1's position, I expect the SD to be the same (in this case, `172  (30)` rather than `172 (30.1)`).

**Comment by benjaminrich** [comment]
While I understand what you are trying to get at, there is no perfect way to do rounding that works in all cases. What you expect (i.e. the mean and SD to be rounded to the same position) isn't necessarily what other people want or expect. For the default rule I prefer the simple approach of 3 significant digits for all numbers, but if that's not what you want then you can change it with your own render function.

**Comment by carbocation** [comment]
Understood - thanks for considering. I'm going to close this.
