### ISSUE TITLE
'na.rm' not working to remove Missings ~

### ISSUE THREAD

**Issue by tgoedecke** [benjaminrich/table1#29]
Benjamin Rich ~
I have only just learned of your table1 package, and I am so glad to be able to use it. I especially appreciate the ease of use of the table1::table1 function. 

My issue is minor, but it seems you have intended to address it. 

To exclude missing data from the output table, your documentation says to use 'na.rm=TRUE' as a parameter setting. When I applied this setting, however, nothing changed in the output. I tried the "deprecated" parameter setting as well ('NAkeep=NULL'), with no further success. 

Here is a code example, with output below:
 
df <- data.frame("X" = c(1, 2, 3,NA, 5), "Y" = c(50:54))
table1::table1(~X + Y, data = df, NAkeep = NULL, na.rm = TRUE)

  | Overall(N=5)
-- | --
X |  
Mean (SD) | 2.75 (1.71)
Median [Min, Max] | 2.50 [1.00, 5.00]
Missing | 1 (20.0%)
Y |  
Mean (SD) | 52.0 (1.58)
Median [Min, Max] | 52.0 [50.0, 54.0]

I appreciate your help ~ thank you!
Trish

**Comment by benjaminrich** [comment]
Hi Trish,

I'm not sure where in the documentation I mention `na.rm`, and `NAkeep` was never an option in this package (maybe you are confusing with another package?), but to get what you want, you should use `render.missing=NULL`:

```r
table1::table1(~X + Y, data = df, render.missing = NULL)
```


  | Overall(N=5)
-- | --
X |  
Mean (SD) | 2.75 (1.71)
Median [Min, Max] | 2.50 [1.00, 5.00]
Y |  
Mean (SD) | 52.0 (1.58)
Median [Min, Max] | 52.0 [50.0, 54.0]

**Comment by tgoedecke** [comment]
Benjamin ~ 
Wow ~ I guess I must've found documentation for a different package by mistake. Thanks so much for your quick reply ~ that's exactly what I needed to know.
best ~
