### ISSUE TITLE
Saving table as self contained html via htmlWidgets::saveWidget does not work

### ISSUE THREAD

**Issue by nebuzoltanszuhai** [benjaminrich/table1#30]
At trying to save the table1 generated table as a self contained html I get the following error:
"Error: $ operator is invalid for atomic vectors"
Is there any trick to still be able to save the table as an html file?

Example code:
--------------

library(boot) 
library(table1)
library(htmlwidgets)

melanoma2 <- boot::melanoma

melanoma2$status <- 
  factor(melanoma2$status, 
         levels=c(2,1,3),
         labels=c("Alive", "Melanoma death", "Non-melanoma death"))

tablee1 <- table1(~ factor(sex) + age + factor(ulcer) + thickness | status, data=melanoma2)

htmlwidgets::saveWidget(tablee1, "table1.html", background = "transparent")

**Comment by HuoJnx** [comment]
You can use this function, in which 'output' represents what you get from the table1.
`
save_table1= function(output,file_name="temp.html"){
    css_path=system.file("table1_defaults_1.0/table1_defaults.css", package="table1")
    css=sprintf('<style type="text/css">@import url(%s);</style>',css_path)
    cat(paste(css,output),file=file_name)
}
`

**Comment by benjaminrich** [comment]
Indeed, the table1 object is not an htmlwidget, but the solution posted by @HuoJnx can be used to save the output as a standalone file. Thanks for posting this. I will close the issue.
