### ISSUE TITLE
Calculating Standard Error of the Mean (SEM)

### ISSUE THREAD

**Issue by nawar82** [benjaminrich/table1#31]
Hi! I am trying to use table1 package to calculate the standard error of the mean with no success. Do you have any idea how to do that please?

**Comment by benjaminrich** [comment]
You can do that with a custom render function. Here is an example:

```r
library(table1)

dat <- data.frame(x=rep(LETTERS[1:3], each=100))
dat$y <- exp(rnorm(nrow(dat)))

rndr <- function(x) {
  s <- stats.default(x)
  s$SEM <- with(s, SD/sqrt(N))
  with(stats.apply.rounding(s), c("",
    "Mean (SEM)"=sprintf("%s (%s)", MEAN, SEM)))
}

table1(~ y | x, data=dat, render.continuous=rndr)
```

<table class="Rtable1">
<thead>
<tr>
<th class='rowlabel firstrow lastrow'></th>
<th class='firstrow lastrow'><span class='stratlabel'>A<br><span class='stratn'>(N=100)</span></span></th>
<th class='firstrow lastrow'><span class='stratlabel'>B<br><span class='stratn'>(N=100)</span></span></th>
<th class='firstrow lastrow'><span class='stratlabel'>C<br><span class='stratn'>(N=100)</span></span></th>
<th class='firstrow lastrow'><span class='stratlabel'>Overall<br><span class='stratn'>(N=300)</span></span></th>
</tr>
</thead>
<tbody>
<tr>
<td class='rowlabel firstrow'><span class='varlabel'>y</span></td>
<td class='firstrow'></td>
<td class='firstrow'></td>
<td class='firstrow'></td>
<td class='firstrow'></td>
</tr>
<tr>
<td class='rowlabel lastrow'>Mean (SEM)</td>
<td class='lastrow'>1.25 (0.137)</td>
<td class='lastrow'>1.62 (0.209)</td>
<td class='lastrow'>1.73 (0.286)</td>
<td class='lastrow'>1.53 (0.127)</td>
</tr>
</tbody>
</table>
