### ISSUE TITLE
feature request, labels not as required argument, labelling under the hood, column selection if needed

### ISSUE THREAD

**Issue by tjebo** [benjaminrich/table1#32]
First of all, nice package

I used it first time today. It generates nice tables!

I find the usage with labels a bit unintuitive though. It is peculiar to me why labels should be a required argument. 

I feel that I often do not *wish* to label my data, because label attributes can sometimes have weird side effects. 
Labelling would ideally not be necessary outside the function. The function should do this under the hood. If the argument is not specified, it would default to the column names... 

It would be way more intuitive it the only required argument would be the data frame. If no other argument is specified, the table would summarise all variables (like in `tableone::CreateTableOne`). 

If this makes weird results, or does not make sense, the variables should be selected by the user, ideally simply as vector string `c(...)` or `list`, or cool would be tidy selection, if you like the tidy verse. It's not difficult to implement tidy selection in your functions, and it's very cool.

This would result in a super intuitive UI, in my opinion. 

Anyways, congrats for the work!

**Comment by tjebo** [comment]
ah, this refers to `table1()` of course

**Comment by benjaminrich** [comment]
Thanks for sharing your feedback and opinions on the package. It's always nice to hear from users. First, I want to point out that the labels are indeed optional, and will fall back to the column names as default if omitted. This may be fine for your personal viewing (e.g. data exploration), but does not result in publication-ready tables in most cases, which is really the purpose of this package. Therefore, I prefer to have the option. 

Second, with regard to the interface. In my opinion, the formula interface is simple, flexible, intuitive and elegant. It is idiomatic R, and has the advantage that you can specify the stratification variable(s) at the same time (if you only supplied the data frame, how would you know what to stratify by? I suppose you would want to use `group_by()` for that).

It seems that you want to use the package for a slightly different purpose than it was originally intended for, which is great. I'm always eager to improve my package and make it appeal to more users. Unfortunately, I don't have the time to implement any major changes right now. But it seems that the sort of thing you want to do can be accomplished with a simple wrapper, like this:

table1.grouped_df <- function(x, ...) {  g <- attributes(x)$groups  v1 <- setdiff(names(x), names(g))  v2 <- setdiff(names(g), ".rows")  formula <- as.formula(sprintf("~ %s | %s",    paste(v1, collapse=" + "), paste(v2, collapse=" + ")))  table1::table1(formula, data=x, ...)}

Here's an example:

library(table1)library(dplyr)set.seed(123)dat <- data.frame(x=rep(LETTERS[1:3], times=sample(20:200, 3)))dat$y <- runif(nrow(dat), 20, 80)dat$z <- exp(rnorm(nrow(dat)))dat %>%  group_by(x) %>%  table1

A
(N=178)B
(N=198)C
(N=33)Overall
(N=409)y




Mean (SD)
49.9 (16.6)
49.9 (17.3)
49.0 (18.4)
49.8 (17.0)
Median [Min, Max]
48.6 [20.0, 79.7]
48.9 [20.4, 80.0]
43.7 [25.0, 79.5]
48.7 [20.0, 80.0]
z




Mean (SD)
1.54 (1.95)
1.36 (1.51)
2.49 (3.95)
1.53 (2.02)
Median [Min, Max]
0.975 [0.0365, 15.0]
0.947 [0.0857, 11.5]
1.13 [0.174, 21.3]
0.976 [0.0365, 21.3]


Jun 27, 2020, 08:25 by notifications@github.com:

**Comment by benjaminrich** [comment]
Thanks for sharing your feedback and opinions on the package. It's always nice to hear from users. First, I want to point out that the labels are indeed optional, and will fall back to the column names as default if omitted. This may be fine for your personal viewing (e.g. data exploration), but does not result in publication-ready tables in most cases, which is really the purpose of this package. Therefore, I prefer to have the option. 

Second, with regard to the interface. In my opinion, the formula interface is simple, flexible, intuitive and elegant. It is idiomatic R, and has the advantage that you can specify the stratification variable(s) at the same time (if you only supplied the data frame, how would you know what to stratify by? I suppose you would want to use `group_by()` for that).

It seems that you want to use the package for a slightly different purpose than it was originally intended for, which is great. I'm always eager to improve my package and make it appeal to more users. Unfortunately, I don't have the time to implement any major changes right now. But it seems that the sort of thing you want to do can be accomplished with a simple wrapper, like this:

```r
table1.grouped_df <- function(x, ...) {
  g <- attributes(x)$groups
  v1 <- setdiff(names(x), names(g))
  v2 <- setdiff(names(g), ".rows")
  formula <- as.formula(sprintf("~ %s | %s",
    paste(v1, collapse=" + "), paste(v2, collapse=" + ")))
  table1::table1(formula, data=x, ...)
}
```

Here's an example:

```r
library(table1)
library(dplyr)

set.seed(123)

dat <- data.frame(x=rep(LETTERS[1:3], times=sample(20:200, 3)))
dat$y <- runif(nrow(dat), 20, 80)
dat$z <- exp(rnorm(nrow(dat)))

dat %>%
  group_by(x) %>%
  table1
```

. | A(N=178) | B(N=198) | C(N=33) | Overall(N=409)
-- | -- | -- | -- | --
y |   |   |   |  
Mean (SD) | 49.9 (16.6) | 49.9 (17.3) | 49.0 (18.4) | 49.8 (17.0)
Median [Min, Max] | 48.6 [20.0, 79.7] | 48.9 [20.4, 80.0] | 43.7 [25.0, 79.5] | 48.7 [20.0, 80.0]
z |   |   |   |  
Mean (SD) | 1.54 (1.95) | 1.36 (1.51) | 2.49 (3.95) | 1.53 (2.02)
Median [Min, Max] | 0.975 [0.0365, 15.0] | 0.947 [0.0857, 11.5] | 1.13 [0.174, 21.3] | 0.976 [0.0365, 21.3]

**Comment by tjebo** [comment]
Cool, thanks for the detailed reply! :)
