### ISSUE TITLE
Example of comma thousands separator

### ISSUE THREAD

**Issue by ldbruce-2018** [benjaminrich/table1#34]
Hi, can you post an example of the table1 function with a comma thousands separator?

**Comment by benjaminrich** [comment]
I would like to make this easier in a future release, but for now, you can try this:

```r
library(table1)

set.seed(123)

dat <- data.frame(x=rep(LETTERS[1:3], times=sample(20:200, 3)))

dat$y <- round(runif(nrow(dat), 1e2, 1e10))

render.continuous <- function(x, ...) {
    with(stats.default(x, ...), c("",
        "Mean (SD)"         = sprintf("%s (%s)",
          signif_pad(MEAN,   3, big.mark=","),
          signif_pad(SD,     3, big.mark=",")),
        "Median [Min, Max]" = sprintf("%s [%s, %s]",
          signif_pad(MEDIAN, 3, big.mark=","),
          signif_pad(MIN,    3, big.mark=","),
          signif_pad(MAX,    3, big.mark=","))))
}

table1(~ y | x, data=dat, render.continuous=render.continuous)
```

  | A(N=178) | B(N=198) | C(N=33) | Overall(N=409)
-- | -- | -- | -- | --
y |   |   |   |  
Mean (SD) | 4,990,000,000 (2,760,000,000) | 4,980,000,000 (2,880,000,000) | 4,830,000,000 (3,060,000,000) | 4,970,000,000 (2,840,000,000)
Median [Min, Max] | 4,770,000,000 [6,250,000, 9,940,000,000] | 4,810,000,000 [63,000,000, 9,990,000,000] | 3,950,000,000 [825,000,000, 9,910,000,000] | 4,780,000,000 [6,250,000, 9,990,000,000]

**Comment by miargentieri** [comment]
Would it be possible to see an example of how to use table1 function with a comma thousands separator for categorical variables? I'm looking at the frequency counts of categorical variables in table1 but would like to be able to add commas to the numbers in the output.
<img width="799" alt="Screen Shot 2020-08-11 at 12 01 17 PM" src="https://user-images.githubusercontent.com/64753618/89889959-73bf1200-dbca-11ea-9468-89ee3e50a373.png">

**Comment by nknowlton** [comment]
This is very helpful and would be a great addition to your examples for formatting.

**Comment by AdamDugan** [comment]
Is there a way to apply the same sort of formatting to the missing data rows? In the table1 function, I only see an argument for "render.missing.default" and not "render.missing" like the other types of values.

**Comment by benjaminrich** [comment]
Hi @AdamDugan. For a while now (since v1.4 I believe) it has been possible to pass `big.mark` to `table1()` directly, and in that case I will also apply to the number of missing values. Like this:

```r
table1(~ y | x, data=dat, big.mark=",")
```

Try it and let me know if that works for you.
