### ISSUE TITLE
Alphabetic order for footnotes 

### ISSUE THREAD

**Issue by tswiebold** [benjaminrich/table1#35]
Hello,

I am trying to create APA footnotes using the table1 function and I cannot seem to figure it out. Instead of the footnote input taking an entire character matrix and creating a single footnote using the entire matrix with rows denoting new lines, it instead iterates through the matrix and creates the same table only using one row at a time. For example I have ten rows and when I use the character matrix in this format it creates 10 identical tables with the only difference being which row is used for the footnote. 

The "footnote" function from the package "kableExtra" is extremely useful and makes APA footnotes for a kable, but the kable is not in APA format. If something like this could be made for table1 it would be awesome!

**Comment by benjaminrich** [comment]
I will look into it. Can you provide a picture of what it should look like?

Jul. 22, 2020, 15:53 by notifications@github.com:

**Comment by tswiebold** [comment]
Hello,

Thank you for such a quick response! The desired footnotes look like this image (a,b,c):

[cid:9f4a5b10-76dc-4762-9a57-d3bd91571e68]
Have a great day,
Theodore

**Comment by benjaminrich** [comment]
Hmm... I can't see the image :(

**Comment by tswiebold** [comment]
How about now?
________________________________

**Comment by tswiebold** [comment]
![image](https://user-images.githubusercontent.com/56325204/88339473-b4c8b280-ccff-11ea-947d-8929f632b9f2.png)

**Comment by benjaminrich** [comment]
It is now possible to have multiple footnotes. I'm not sure it is quite as easy as you might like it, but it is possible to get what you are asking for. Here is and example:

```r
dat <- data.frame(x=rep(LETTERS[1:3], times=c(23, 34, 5)))

dat$y1 <- rnorm(nrow(dat))
dat$y2 <- rnorm(nrow(dat))
dat$y3 <- rnorm(nrow(dat))

label(dat$y1) <- "First<sup>a</sup>"
label(dat$y2) <- "Second<sup>b</sup>"
label(dat$y3) <- "Third<sup>c</sup>"

footnote <- c(
  "<sup>a</sup> An impressive result.",
  "<sup>b</sup> Could even be in <i>italics</i>.",
  "<sup>c</sup> But you have to know some HTML &#x1F60E;")

table1(~ y1 + y2 + y3 | x, data=dat, render="Mean", footnote=footnote)
```

![image](https://user-images.githubusercontent.com/17572252/109099953-f08e8500-76f1-11eb-839d-4d047ed86fe5.png)

**Comment by tswiebold** [comment]
You rock @benjaminrich! I am never one to complain of difficulty. I just find it more secure to be able to completely create and format these tables in R instead of importing them into excel and manipulating that way. Thank you!

**Comment by benjaminrich** [comment]
Thank you!
