### ISSUE TITLE
Request/Suggestion: render.varlabel option to wrap lengthy labels to two lines

### ISSUE THREAD

**Issue by cochetti** [benjaminrich/table1#36]
Firstly, thank you!  **table1** is a fantastic package and is really great and intuits many of the needs for those of us producing results (especially so called Table 1s) for medical publishing. I rely on your package a lot. 

I am using **table1** with variables from survey instruments. The variable labels are derived from controlled terminologies for these instruments which list the entire survey prompt in the label. Because of this labeling convention, some of the labels end up being quite lengthy. Would it be possible to include an optional flag such as `wrap = TRUE` or `wrap = 30` in the function call for table1 which would be inherited by render.varlabel and then parse the label string into segments of say a provided length?  

I recognize that you cannot know the output size and the CSS styles and other factor will impact how the final results are rendered. However, I think when you look at the example table below, you can see how the option to truncate and wrap some of the varlabels would help. 

![table1 label wrap request](https://user-images.githubusercontent.com/49292397/92839277-c2b8bc80-f3ad-11ea-9c9d-5eff8c335574.png)

**Comment by cochetti** [comment]
Okay, after playing with this trying to insert various line breaks and text handlers, I saw your comment about custom CSS formatting.  Played with that for awhile only to notice that the default CSS script was overriding my edits. 

I have a workaround by adding `white-space: normal;` to the `.Rtable1 .firstrow.rowlabel` style. However, I cannot for the life of me figure out how to overwrite the `<td>` cells to the right. So for now it word-wraps within the cell, but doesn't overwrite the blank cells to the right of it.  I tried using `overflow` and `display` styles to handle it to no avail.

**Comment by benjaminrich** [comment]
Hi,

Thanks for the suggestion. I have 2 possible suggestions for how to achieve this.

1. Using the `str_wrap()` function from the `stringr` package:

```r
library(table1)
library(stringr)
set.seed(123)

n <- 200
dat <- data.frame(
  x=sample(LETTERS[1:3], n, replace=T),
  y=runif(n, 55, 85),
  z=runif(n, 100, 170))

label(dat$y) <- "Short"
label(dat$z) <- "Something really really long that needs to be wrapped"


for (v in c("y", "z")) {
  label(dat[[v]]) <- gsub("\n", "<br/>", stringr::str_wrap(label(dat[[v]]), 20))
}

table1(~ y + z | x, data=dat)
``` 

You need to replace the newlines (`"\n"`) with the HTML sequence `"<br/>"`

![image](https://user-images.githubusercontent.com/17572252/92974716-d1a67a00-f454-11ea-9610-a68f7afb0519.png)

2. If you are using R markdown, then embedding this CSS should do the trick:

```css
.Rtable1 td.rowlabel {
  white-space: normal;
  width: 2in;
}
```
![image](https://user-images.githubusercontent.com/17572252/92975720-e2f08600-f456-11ea-869f-1b638f13cc92.png)

Obviously, you can control the `width` to your liking.

Hope this helps!

**Comment by benjaminrich** [comment]
Closing this issue as I've received no feedback from OP.

**Comment by cochetti** [comment]
Thank you for your response. My apologies this got filtered in my email. 

I eventually found the .css way to achieve my desired result after struggling with it for a good 6 hours. I found that adding \n and other wrapping mechanisms were not carried over from R Markdown to the HTML output document. 

I ended up customizing your default .css file and delete the `white-space` default setting from `nowrap` to `normal` or another suitable setting. Even when I tried the approach you list above I found that your css file was taking priority over my own stypel changes and it was not carrying through to the final file. The other nice things about this solution was that it was still responsive as the window was resized and adjusted the cell as necessary. 

I really had hoped to find a way to let it "overflow" the cell rightwards and then wrap as necessary upon hitting the right edge of the table. I was not able to accomplish this however. It seems that there was "something" being generated to preserve the other header row cells above the data columns. Whenever I tried to overflow and write over this text it ended up wrapped in the first cell or truncated by the placeholder contained in the 2nd column.

**Comment by cochetti** [comment]
I think you missed my goal in my second message...  Here is a modification of your example to show a bit more clearly what I meant. 

![image](https://user-images.githubusercontent.com/49292397/94651799-07f24f00-02c7-11eb-899d-eccdcc95f8bd.png)

**Comment by benjaminrich** [comment]
You can do this with javascript. If you are using Rmd format, put this at the bottom of your file:

```html
<script>
$(document).ready(function() {
  let colspan = $('.Rtable1 table > tbody > tr:first > td').length;
  $('.Rtable1 td.rowlabel').css({'width': '2in', 'white-space': 'normal'});
  $('.Rtable1 td.firstrow').attr('colspan', colspan);
  $('.Rtable1 td.firstrow ~ td').remove();
});
</script>
```

It might not work if you have more than one table in the document (unless they have the same number of columns); in that case you would need to adapt it. Here is the result I got:

![image](https://user-images.githubusercontent.com/17572252/94782209-e5306b00-0398-11eb-8633-4ce1a6268f4e.png)
