### ISSUE TITLE
customize missing rendering

### ISSUE THREAD

**Issue by mplessz** [benjaminrich/table1#37]
Hello
Thanks for this very useful package.
I was wondering if you could give an example of how to customize the rendering of missing values: labels and statistics.
![image](https://user-images.githubusercontent.com/23453716/98236256-5ac4c380-1f63-11eb-9dc7-e613df5da2ed.png)

I currenlty use the option : `render.categorical="PCTnoNA%"`  ( #21 , very, very useful) .

I would like to change the label and the figures displayed for the line "Missing": 
I write in French so I would like to write : "Manquantes" (other whatever : "N Missing"...)
I have tried to use `render.missing = "FREQ"` but it did not work (it added a buch of rows to the table).
Additionnaly, I would like to chose the thousand separator as in issue #34. I tried to adapt your code for 
`render.strata` and `render.categorical` , but I failed.

I have generated the exemple above using your mockup data, with missing values : 
``` r 
# generating data with missing values
set.seed(123)
dat <- data.frame(x=rep(LETTERS[1:3], times=sample(10000:99999, 3)))
dat$y <- sample(LETTERS[4:7], nrow(dat), replace=T, prob=c(0.1, 0.2, 0.3, 0.4))
dat$y[1:350] <- NA 

# table
table1(~ y | x, data=dat,  
			 render.categorical = "PCTnoNA%"
			 )
```
Thanks !

**Comment by benjaminrich** [comment]
This works, but isn't as elegant as I would like:

```r
# Custom function to render missing values
render.missing <- function(x, ..., newlabel="Manquantes") {
    setNames(render.missing.default(x, ...), newlabel)
}

# table
table1(~ y | x, data=dat,
       render.categorical = "PCTnoNA%",
       render.missing=render.missing)
```
![image](https://user-images.githubusercontent.com/17572252/99727145-86789b00-2a85-11eb-9829-3698967054ad.png)

**Comment by mplessz** [comment]
Yes, it works fine. I just tested it on my big table. Thank you

**Comment by samuelsaari** [comment]
How would you customize the decimal places for the missing values? The default seems to be one, but would need 2 decimal places.


```
library(table1)
library(reprex)

# create data
f <- function(x, n, ...) factor(sample(x, n, replace=T, ...), levels=x)
set.seed(427)
n <- 146
dat <- data.frame(id=1:n)
dat$treat <- f(c("Placebo", "Treated"), n, prob=c(1, 2)) # 2:1 randomization
dat$age   <- sample(18:65, n, replace=TRUE)
dat$sex   <- f(c("Female", "Male"), n, prob=c(.6, .4))  # 60% female
dat$wt    <- round(exp(rnorm(n, log(70), 0.23)), 1)

# Add some missing data
dat$wt[sample.int(n, 5)] <- NA


# render
my.render.cont <- function (x, ...) {
  with(lapply(stats.default(x), # had digits=1,digits.pct=1
              round_pad, digits=2,digits.pct=2,round.median.min.max = F,round.integers = F, ...), 
       c("",
         `Mean (SD)`         = sprintf("%s (%s)", MEAN, SD))) # was %s for both
}


my.render.cat <- function(x) {
  c("", sapply(stats.default(x,round.median.min.max = F,round.integers = F),
               function(y) with(y, sprintf("%d (%0.2f %%)", FREQ, PCT))))
}


# OK but only one decimal in missing percentages
table1(~ age + sex + wt | treat, 
       data=dat,
       render.continuous=my.render.cont, 
       render.categorical=my.render.cat) 


# produces error..
table1(~ age + sex + wt | treat, 
       data=dat,
       render.continuous=my.render.cont, 
       render.categorical=my.render.cat,
       render.missing=my.render.cat)
#... Error in eval(substitute(expr), data, enclos = parent.frame()) :
# not that many frames on the stack
```
