### ISSUE TITLE
Create output to use with officer / flextable packages

### ISSUE THREAD

**Issue by loeffju1** [benjaminrich/table1#40]
I like the functionality to create table1 outputs in a nice style. However, often it is necessary to copy and paste the output into a Word or Powerpoint document, where it requires considerable post-editing. I wonder if there is any possibility to create a table1 output object that can be used by the officer / flextable packages to embed it in such Office documents?

**Comment by benjaminrich** [comment]
I agree and I have been thinking about something along these lines for a long time. One of these days I will get around to implementing it.

**Comment by benjaminrich** [comment]
Check out the new release, v1.4. In has the new function `t1flex()`. See if that suits your needs.
