### ISSUE TITLE
Two inquires about Table1 package

### ISSUE THREAD

**Issue by MahmoudDI** [benjaminrich/table1#41]
Hi,

I have been using Table1 package since quite some time. I am really happy to use it as it saves a lot of time and efforts. Thank you so much for your efforts in developing it!

I have two inquires which I have been looking for:

**First inquiry:**
I have been using the following code to make a characteristics table:
library(table1)
data(lalonde)
lalonde$treat    <- factor(lalonde$treat, levels=c(0, 1, 2), labels=c("Control", "Treatment", "P-value"))
lalonde$married  <- as.logical(lalonde$married == 1)
lalonde$nodegree <- as.logical(lalonde$nodegree == 1)
rndr <- function(x, name, ...) {
  if (length(x) == 0) {
    y <- lalonde[[name]]
    s <- rep("", length(render.default(x=y, name=name, ...)))
    if (is.numeric(y)) {
      p <- t.test(y ~ lalonde$treat)$p.value
    } else {
      p <- chisq.test(table(y, droplevels(lalonde$treat)))$p.value
    }
    s[2] <- sub("<", "&lt;", format.pval(p, digits=3, eps=0.001))
    s
  } else {
    render.default(x=x, name=name, ...)
  }
}
rndr.strat <- function(label, n, ...) {
  ifelse(n==0, label, render.strat.default(label, n, ...))
}
table1(~ married + nodegree  | treat,
       data=lalonde, droplevels=F, render=rndr, render.strat=rndr.strat, overall=F)

The output would yield a chi-square statistic with Yates correction (default). I want a way to remove the correction and just produce a chi-square p-value without correction. I tried adding "chisq.correct=FALSE" or "correct=F" in several places in the codes but that did not work. Any advice on how I can do that? or if you can help me by editing the above code?

**Second inquiry:**

I want to add one column which has the N (without percentage) of available data for each variable before the groups. See the example:

![download](https://user-images.githubusercontent.com/47884729/104599732-3256f500-5689-11eb-842d-f881f6cc31ac.png)

Thank you so much in advance.

**Comment by benjaminrich** [comment]
For the first inquiry, if you do it like this it should work:

```r
p <- chisq.test(table(y, droplevels(lalonde$treat)), correct=FALSE)$p.value
```

Regarding the second inquiry, that is not possible at the moment but it is a great suggestion and I would like to implement something like this in the future.

**Comment by benjaminrich** [comment]
PR #44 changes the way to add a p-value column to the table, and also resolves your second inquiry. With those changes you will be able to do it like this:

```r
library(table1)
library(MatchIt) 

set.seed(123)

data(lalonde)

lalonde$treat    <- factor(lalonde$treat, levels=c(0, 1), labels=c("Control", "Treatment"))
lalonde$married  <- as.logical(lalonde$married == 1)
lalonde$nodegree <- as.logical(lalonde$nodegree == 1)

# Add some missing values
lalonde$married[sample(1:nrow(lalonde), 9)]  <- NA

mypvalue <- function(x) {
    y <- unlist(x)
    g <- factor(rep(1:length(x), times=sapply(x, length)))
    if (is.numeric(y) && nlevels(g)==2) {
        p <- t.test(y ~ g)$p.value
    } else if (is.numeric(y)) {
        fstat <- summary(lm(y ~ g))$fstatistic
        p <- 1 - pf(fstat[1], fstat[2], fstat[3])
    } else {
        p <- chisq.test(table(y, g), correct=F)$p.value
    }
    sub("<", "&lt;", format.pval(p, digits=3, eps=0.001))
}

extra.col=list(
    "N"       = function(x, name, ...) { sum(!is.na(c(unlist(x)))) },
    "P-value" = function(x, name, ...) { c("", mypvalue(x)) }
)

table1(~ married + nodegree | treat, data=lalonde, overall=F, extra.col=extra.col, extra.col.pos=1)
```
![image](https://user-images.githubusercontent.com/17572252/110421728-0f830480-806c-11eb-89ef-64563c01ed9a.png)

**Comment by MahmoudDI** [comment]
Thank you so much for your generous response. I really appreciate it.
I tried now to just copy and paste the same codes you just typed. At first, it worked well and resulted in the the same table you presented. However, it does not work with me now. The p-value and N columns do not appear. See what it shows to me:
![image](https://user-images.githubusercontent.com/47884729/110426173-aecce980-80b6-11eb-90a1-3ce06b5d5778.png)

Any hint about how I can resolve this and have the two columns appear again? or is there a way we can slightly edit the previous code (the first code I sent) to add the N column?

Thanks in advance.

**Comment by benjaminrich** [comment]
I don't know. That seems strange. Are you sure you're using the right code? You can install it like this:

```r
remotes::install_github("benjaminrich/table1#44")
```

**Comment by MahmoudDI** [comment]
I tried to do that again and used this code (just copied it and pasted it without any changes), but still does not work. Anyway, thank you so much for responding to me, and thanks for developing this amazing package.

Best regards

**Comment by benjaminrich** [comment]
PR #44  has been merged. Maybe try again after updating. It should work.
