### ISSUE TITLE
sub-group

### ISSUE THREAD

**Issue by nsk64** [benjaminrich/table1#46]
Is it possible to have only 2 columns, the first for a sub-group of patients and the 2nd column for all patients?

**Comment by benjaminrich** [comment]
Yes, but not using the formula interface, so it might be a little less convenient. Here is a small example:

```r
library(boot)

labels <- list(variables=list(
        age       = "Age (years)",
        thickness = "Thickness (mm)"))

strata <- list(
    "Female patients" = subset(melanoma, sex==0),
    "All patients"    = melanoma)

table1(strata, labels)
```

![image](https://user-images.githubusercontent.com/17572252/113858614-ed1afe80-9771-11eb-861e-db9e1e0b14b4.png)

**Comment by nsk64** [comment]
Many thanks

very clear and efficient.

Best regards

Nicolas



________________________________
De : Benjamin Rich ***@***.***>
Envoyé : mercredi 7 avril 2021 13:22
À : benjaminrich/table1
Cc : SIMON Nicolas; Author
Objet : Re: [benjaminrich/table1] sub-group (#46)


EMAIL EXTERNE - TRAITER AVEC PRÉCAUTION LIENS ET FICHIERS

Yes, but not using the formula interface, so it might be a little less convenient. Here is a small example:

library(boot)

labels <- list(variables=list(
        age       = "Age (years)",
        thickness = "Thickness (mm)"))

strata <- list(
    "Female patients" = subset(melanoma, sex==0),
    "All patients"    = melanoma)

table1(strata, labels)

[image]<https://urldefense.com/v3/__https://user-images.githubusercontent.com/17572252/113858614-ed1afe80-9771-11eb-861e-db9e1e0b14b4.png__;!!JQ5agg!KPJdxqmgbVsEcV5toHL0Du4DDcMorsGCvhf9MRrRj8EhRJ1acF-znwEJ4J3LZVHVngxd$>

-
