### ISSUE TITLE
Remove "%" value for categorical data (to allow better copy pasting in excel)

### ISSUE THREAD

**Issue by unlimited67g** [benjaminrich/table1#47]
Hello,
First, thanks for the package!

I would like to make one table without the "%", is that possible?
The idea is to facilitate the copy/paste of the html to excel :   With the %, each cell is a character cell in excel with the number and the percentage...
Without, it will be a normal cell with number.

![image](https://user-images.githubusercontent.com/55018594/114521388-a7af7300-9c42-11eb-9351-09487ee0ec69.png)

The other ways i see, less elegant, and not sure if it could work with table1 object,   are:
- Use stringi::str_replace() to remove evererything inside "()"
- Use tidyr::separate() to create 

As well : Could be a good thing anyway to remove the percentage or to have it in another column; for example to use formattable after and do conditional formatting ?

reprex;
```r
library(boot) 
table1(~ factor(sex)  | status, data=melanoma)
```

Thanks !!

**Comment by benjaminrich** [comment]
In fact, it is quite easy. For your example:

```r
library(table1) 
library(boot) 

melanoma$status <- factor(melanoma$status, 
         levels=c(2,1,3),
         labels=c("Alive", # Reference
                  "Melanoma death", 
                  "Non-melanoma death"))

table1(~ factor(sex)  | factor(status), data=melanoma, render.categorical="FREQ")
```

![image](https://user-images.githubusercontent.com/17572252/114540949-1df0ad00-9c24-11eb-9bb6-3aba5df98c5e.png)

**Comment by unlimited67g** [comment]
oh, thanks, perfect!
I didn't see it in the help of table1.

i was using your hint with `render.categorical` to have  big.mark=" " :

```
library(table1) 
library(boot) 

melanoma$status <- factor(melanoma$status, 
         levels=c(2,1,3),
         labels=c("Alive", # Reference
                  "Melanoma death", 
                  "Non-melanoma death"))



render.strat <- function (label, n, ...) {
    sprintf("<span class='stratlabel'>%s<br><span class='stratn'>(N=%s)</span></span>",
        label, prettyNum(n, big.mark=" "))
}

render.categorical <- function(x, ...) {
    c("", sapply(stats.apply.rounding(stats.default(x)), function(y) with(y,
      sprintf("%s (%s%%)", prettyNum(FREQ, big.mark=" "), PCT))))
}
# Make it ten times so we can see big marks : 
melanoma_10times <- purrr::map_dfr(seq_len(15), ~melanoma)
table1(~ factor(sex)  | status, data=melanoma_10times , 
render.categorical=render.categorical,
render.strat=render.strat )
```
How could i combine with render.strat="FREQ" ? 
I tried this but not working : 
[ Thousands seperator #42 ](https://github.com/benjaminrich/table1/issues/42)

```
table1(~ factor(sex)  | status, data=melanoma_10times, 
       render.categorical="FREQ",
       big.mark=" ")
```

**Comment by benjaminrich** [comment]
You are right! If you can install the latest GitHub version, it should work now.

```r
table1(~ factor(sex)  | status, data=melanoma_time100, render.categorical="FREQ", big.mark=" ")
```

![image](https://user-images.githubusercontent.com/17572252/114795667-1c76d000-9d5d-11eb-847a-5c27713b803e.png)

**Comment by unlimited67g** [comment]
Yes it worked with the last version, thanks !

There is now some table1's in the Vaccination dashboard of the French Health Agency thanks to you !



ps : i edited my code to match your data frame name `melanoma_time100 `

**Comment by benjaminrich** [comment]
Outstanding! This change will be incorporated in the next release (coming soon).
