### ISSUE TITLE
Rendering only Present (Absent/Present ; 0/1)

### ISSUE THREAD

**Issue by spiralparagon** [benjaminrich/table1#48]
Absolutely love this package, but I'm curious if there's a setting for the categorical renderer to only render one value when for example displaying dichotomous values, for example.

|Diabetes|
- Absent - %
- Present - %

Into
|Diabetes|
- Present - %

(i.e leaving it up to the reader to infer 100%- whatever % is present)

This would halven the Table 1 and make it more fitting for some publications.

**Comment by benjaminrich** [comment]
Yes, this makes sense, as it is more concise. It is not the default for various reasons, but it can be achieved in different ways. Here is one possibility, using the melanoma example for illustration:

```r
library(boot) 

melanoma$status <- 
  factor(melanoma$status, 
         levels=c(2,1,3),
         labels=c("Alive", # Reference
                  "Melanoma death", 
                  "Non-melanoma death"))

melanoma$ulcer <- as.logical(melanoma$ulcer)

label(melanoma$ulcer) <- "Ulceration Present &mdash; no. (%)"
label(melanoma$age)   <- "Age (years)"

rndr <- function(x, ...) {
    y <- render.default(x, ...)
    if (is.logical(x)) y[2] else y
}

table1(~ ulcer + age | status, data=melanoma, render=rndr)
```

![image](https://user-images.githubusercontent.com/17572252/115968143-4de15f80-a504-11eb-9857-96adfddb477b.png)

**Comment by spiralparagon** [comment]
Thank you! Terrible at R functional code; Looks like this will work for logical factors, taking out y[2] first, is there any way to make this work for categorical values?

**Comment by benjaminrich** [comment]
It's up to you how you want to do it, but I would use `logical` here because it is a binary condition (CVD yes/no). Here's how I would doing, using simulated data as an example:

```r
library(table1) 

set.seed(123)
n <- 324
dat <- data.frame(id=1:n)
dat$age <- round(runif(n, 40, 80))
dat$weight <- round(runif(n, 40, 120))
dat$weight[sample(1:n, round(0.2*n))] <- NA
dat$cvd <- sample(c("Present", "Absent"), n, replace=T)

# Define a new logical for CVD present
dat$cvdPresent <- dat$cvd == "Present"

rndr <- function(x, ...) {
    y <- render.default(x, ...)
    if (is.logical(x)) y[2] else y
}

label(dat$age)        <- "Age (years)"
label(dat$weight)     <- "Weight (kg)"
label(dat$cvdPresent) <- "CVD &mdash; no. (%)"

table1(~ age + weight + cvdPresent, data=dat, render=rndr)
```

![image](https://user-images.githubusercontent.com/17572252/116006457-61122f00-a5d9-11eb-89db-91c01ef07add.png)

**Comment by christin-puthur** [comment]
Is it also possible to use render to show only two out of three categories in the table?

**Comment by marisadyw** [comment]
Thanks for the functional code @benjaminrich - How do you apply the rndr function to only specific categorical variables in your table1 and not to all categorical variables?

**Comment by benjaminrich** [comment]
@marisadyw, you should be able to use the same approach as in #94.

**Comment by evansklodge** [comment]
Can anyone explain how to modify this code to include missing values, as well?

rndr <- function(x, ...) {
    y <- render.default(x, ...)
    if (is.logical(x)) y[2] else y
}

I have logical variables that also have missing responses - the code as currently written suppresses missing values from the table1 output. See below for repress (copied and edited slightly from previous):

set.seed(123)
n <- 324
dat <- data.frame(id=1:n)
dat$age <- round(runif(n, 40, 80))
dat$weight <- round(runif(n, 40, 120))
dat$weight[sample(1:n, round(0.2*n))] <- NA
dat$cvd <- sample(c("Present", "Absent"), n, replace=T)

# Define a new logical for CVD present
dat$cvdPresent <- dat$cvd == "Present"

#Replace some random number of "cvdPresent" with NA
dat$cvdPresent[c(1:10)] <- NA

rndr <- function(x, ...) {
    y <- render.default(x, ...)
    if (is.logical(x)) y[2] else y
}

label(dat$age)        <- "Age (years)"
label(dat$weight)     <- "Weight (kg)"
label(dat$cvdPresent) <- "CVD &mdash; no. (%)"

table1(~ age + weight + cvdPresent, data=dat, render=rndr)

**Comment by jwang-lilly** [comment]
@benjaminrich, table1 is my favorite table making tool.  One question: For categorical variables, is there a way to display proportion at row level instead of column level which is default?

**Comment by benjaminrich** [comment]
@jwang-lilly, have a look at #13.
