### ISSUE TITLE
How to show p-value for ANOVA with unequal group sizes?

### ISSUE THREAD

**Issue by ehickman0817** [benjaminrich/table1#51]
Thank you so much for this package - I am really enjoying using it! I would like to add p-values and was using the function defined in the vignette. I have more than two groups, so I wanted to use an ANOVA. I am able to get the ANOVA to work independently of the p-value function, but when I run the p-value function as part of the table1 function, I get an error about unequal group sizes. I tried using the Kruskal Wallis test instead, and that worked just fine. Is there any workaround for the ANOVA? 
```
pvalue <- function(x, ...) {
  # Construct vectors of data y, and groups (strata) g
  y <- unlist(x)
  g <- factor(rep(1:length(x), times=sapply(x, length)))
  if (is.numeric(y)) {
    # For numeric variables, perform an ANOVA
    p <- summary(aov(y ~ g, x))[[1]][["Pr(>F)"]][1]
  } else {
    # For categorical variables, perform a chi-squared test of independence
    p <- chisq.test(table(y, g))$p.value
  }
  # Format the p-value, using an HTML entity for the less-than sign.
  # The initial empty string places the output on the line below the variable label.
  c("", sub("<", "&lt;", format.pval(p, digits=3, eps=0.001)))
}
```
And the errors I get are:
```
Error in (function (..., row.names = NULL, check.rows = FALSE, check.names = TRUE,  : 
  arguments imply differing number of rows: 28, 21, 27 
```
```
Error during wrapup: arguments imply differing number of rows: 28, 21, 27
```
Any help you could provide would be great! I would also love any help on writing the p-value function such that if the data are normally distributed, an ANOVA is run, while if the data are non-normally distributed, a Kruskal-Wallis test is run. I am pretty new at R so let me know if you need any other info. Thanks in advance!

**Comment by benjaminrich** [comment]
Hi. Sorry for the delay.

First, for the error you are getting, the fix is very simple: just change `aov(y ~ g, x)` to `aov(y ~ g)` (i.e., without the second argument).

As to your question, the first thing you have to consider is how you are going to determine whether or not the data are normally distributed I am not going to make any recommendations here, because it is a tricky subject and **there is no surefire way to do it** (I can't emphasize this enough). But suppose, for the sake of argument, and you are okay with using the Shapiro-Wilk test for this purpose (see `?shapiro.test`). Then, you could use that to check the distribution of the dependent variable within each group and reject normality overall if any of the individual tests rejects it.

Here is a complete example:

```r
library(table1)

set.seed(1234)

dat <- data.frame(groups=rep(LETTERS[1:3], times=c(56, 42, 54)))

dat$obs1 <- sample(c("Male", "Female"), nrow(dat), replace=T)
dat$obs2 <- rnorm(nrow(dat), 15, 4)
dat$obs3 <- runif(nrow(dat), 1, 100)

pvalue <- function(x, ...) {
  # Construct vectors of data y, and groups (strata) g
  y <- unlist(x)
  g <- factor(rep(1:length(x), times=sapply(x, length)))
  if (is.numeric(y)) {
    # check for normality using Shapiro-Wilk test
    swtest <- sapply(tapply(y, g, shapiro.test), getElement, "p.value")
    if (all(swtest > 0.05)) {
        # If all p-values are >0.05 we assume normality and use ANOVA
        p <- summary(aov(y ~ g))[[1]][["Pr(>F)"]][1]
        symbol <- "&dagger;"
    } else {
        # Otherwise, reject normality and use Kruskal-Wallis
        p <- kruskal.test(y, g)$p.value
        test <- "Kruskal-Wallis"
        symbol <- "&ddagger;"
    }
  } else {
    # For categorical variables, perform a chi-squared test of independence
    p <- chisq.test(table(y, g))$p.value
    symbol <- "*"
  }
  # Format the p-value, using an HTML entity for the less-than sign.
  # The initial empty string places the output on the line below the variable label.
  c("", paste0(sub("<", "&lt;", format.pval(p, digits=3, eps=0.001)), "<sup>", symbol, "</sup>"))

}

footnote <- c(
    "<sup>*</sup> Chi-squared test",
    "<sup>&dagger;</sup> ANOVA test",
    "<sup>&ddagger;</sup> Kruskal-Wallis test")

table1(~ obs1 + obs2 + obs3 | groups, data=dat, overall=F, extra.col=list(`P-value`=pvalue), footnote=footnote)
```

![image](https://user-images.githubusercontent.com/17572252/118405082-db1b5e00-b643-11eb-941c-92265aa55eea.png)

**Comment by ehickman0817** [comment]
Thank you so much for your help! I really appreciate it. I will try it out and let you know how it goes!

**Comment by ehickman0817** [comment]
I just tried it out and it worked great. I have been reading a lot about normality testing and agree that it is really tricky, but it is useful to have this code as a template regardless. Like I said, loving your package, thanks for making it!
