### ISSUE TITLE
Having problem with running my table1 codes with the new version 1.4.

### ISSUE THREAD

**Issue by leilaasl** [benjaminrich/table1#53]
Hi,
Thank you for this amazing package. 
I have trouble using my previous code for Table1 using the update version of 1.4.1.
Here is a simple code which I was using with the old version of Table1:

```
myrendercont2 <- function (x)
{
    with(lapply(stats.default(x), signif_pad2), c("",
                                                  `Mean (CV%)` = sprintf("%s (%s%%)", MEAN, CV),
                                                  `Median [Min, Max]` = sprintf("%s [%s, %s]", MEDIAN, MIN, MAX)))
}

myrendercat <- function(x) {
    c("", sapply(stats.default(x), function(y) with(y,
                                                    sprintf("%d (%0.0f %%)", FREQ, PCT))))
}

table1(~ sex+age+bmi+weight+ethnic+race|sddose, data=demog,topclass="Rtable1-zebra Rtable1-grid Rtable1-shade Rtable1-times",render.continuous=myrendercont2, render.categorical=myrendercat,droplevels=T,overall=NULL)
```

However, after updating my table1 package, I have received the following error message:

```
Error in (function (x, digits = NULL, width = NULL, format = NULL, flag = "",  : 
  unsupported type 
```

I would appreciate if you may have time to check it.

Thank you,
Leila

**Comment by benjaminrich** [comment]
Maybe it has to do with the function `signif_pad2()` you are using. Can you post that function's definition? Is there a reason why the packages `signif_pad()` function does not do what you want?

**Comment by leilaasl** [comment]
```
signif_pad2<-function (x)
{signif_pad(x,3,round.integers = FALSE)}
```

**Comment by benjaminrich** [comment]
I am able to run your code on some sample data I generated without any errors:

```r
library(table1)

set.seed(123)

n <- 152
demog <- data.frame(
    sex    = factor(sample(c("M", "F"), n, replace=T)),
    age    = runif(n, 18, 80),
    bmi    = runif(n, 16, 40),
    weight = runif(n, 40, 120),
    ethnic = factor(sample(c("AAA", "BBB"), n, replace=T)),
    race   = factor(sample(c("CCC", "DDD"), n, replace=T)),
    sddose = factor(sample(c("1 mg", "2 mg"), n, replace=T)))

signif_pad2 <- function (x) {
    signif_pad(x, 3, round.integers = FALSE)
}

myrendercont2 <- function (x) {
    with(lapply(stats.default(x), signif_pad2), c("",
            `Mean (CV%)` = sprintf("%s (%s%%)", MEAN, CV),
            `Median [Min, Max]` = sprintf("%s [%s, %s]", MEDIAN, MIN, MAX)))
}

myrendercat <- function(x) {
    c("", sapply(stats.default(x), function(y) with(y,
                sprintf("%d (%0.0f %%)", FREQ, PCT))))
}

table1(~ sex+age+bmi+weight+ethnic+race|sddose, data=demog,topclass="Rtable1-zebra Rtable1-grid Rtable1-shade Rtable1-times",render.continuous=myrendercont2, render.categorical=myrendercat,droplevels=T,overall=NULL)
```

![image](https://user-images.githubusercontent.com/17572252/118873093-546eb700-b8b7-11eb-9123-4b0fcb490e97.png)

So, I'm not sure what is causing your issue. Can you provide any more information?

**Comment by leilaasl** [comment]
Thanks, I think the problem comes from my dataset, since I have one observation for some dose levels and that is why it cannot calculate CV and signif_pad may gives and error. I changed my function and it is okay now:

myrendercont1 <- function(x) {
    with(stats.apply.rounding(stats.default(x), digits=3), c(" "=sprintf("%s", MEAN)))
}

However, I am not sure if I can use the following code to render to word:
t1kable(table1(~ sex+age+bmi+weight+ethnic+race|sddose, data=demog,topclass="Rtable1-zebra Rtable1-grid Rtable1-shade Rtable1-times",render.continuous=myrendercont1, render.categorical=myrendercat,droplevels=T,overall=NULL))

it gives me an error:
Error in rbind(deparse.level, ...) : 
  numbers of columns of arguments do not match


Thanks.

**Comment by benjaminrich** [comment]
I found the issue that was causing your original error and have pushed a fix (use `remotes::install_github(...)` to install it). Your original code should run now.

I'm looking into your second error.

**Comment by benjaminrich** [comment]
I'm still not sure about your second error, but for `word_document` output with R markdown I would recommend using `t1flex()` instead of `t1kable()`. You won't get the same formatting as you do with HTML output, but that is a limitation of the way this works. Instead, it will look like this:

![image](https://user-images.githubusercontent.com/17572252/118887698-b1bf3400-b8c8-11eb-8c12-26d5ac655003.png)

**Comment by leilaasl** [comment]
> I found the issue that was causing your original error and have pushed a fix (use `remotes::install_github(...)` to install it). Your original code should run now.
> 
> I'm looking into your second error.

Thanks, yes it works now.  I appreciate your support and enjoy Table1!
