### ISSUE TITLE
Calculate complete "Overall" value by category in the presence of missing data

### ISSUE THREAD

**Issue by gueyenono** [benjaminrich/table1#57]
This question is a follow-up to question #21. In case you have some `NA` values in your data, is there a way to force the rendered table to compute the "Overall" value  for each category? The goal is for the "Overall" value to be a count of all "complete" (non-NA) values in each category. In the "mandatory" reprex below, `N` for Group 1 would be 18 and it would be 16 for Group 2.

```
library(table1)

set.seed(123)

mydata <- data.frame(
  group1 = sample(letters[1:5], size = 20, replace = TRUE),
  group2 = sample(letters[6:10], size = 20, replace = TRUE)
)

mydata$group1[c(1, 10)] <- NA
mydata$group2[c(5, 12, 15, 19)] <- NA

label(mydata$group1) <- "Group 1"
label(mydata$group2) <- "Group 2"

table1(~ group1 + group2, 
       data = mydata,
       render.missing = NULL,
       render.categorical="FREQ (PCTnoNA%)")
```
![table_reprex](https://user-images.githubusercontent.com/8573955/122763343-d7db4980-d263-11eb-8059-a2565fefd270.png)

 Thank you.

**Comment by benjaminrich** [comment]
Yes, it's possible. Here's one way to do it:

```r
rndr <- function(x, ...) {
    if (is.factor(x) || is.character(x)) {
        c(render.default(x, ...), c(`Overall N`=sum(!is.na(x))))
    } else {
        render.default(x, ...)
    }
}

table1(~ group1 + group2, 
       data = mydata,
       render.missing = NULL,
       render.categorical = "FREQ (PCTnoNA%)",
       render = rndr)
```

![image](https://user-images.githubusercontent.com/17572252/122765614-b03dae80-d26e-11eb-9db7-9b976cb158e9.png)

**Comment by gueyenono** [comment]
Nice and clean solution. Thank you very much.

**Comment by benjaminrich** [comment]
I was just going to add that another way to include this information would be to use the space in the same row as the variable label, like this:

```r
rndr <- function(x, ...) {
    r <- render.default(x, ...)
    if (is.factor(x) || is.character(x)) {
        r[1] <- sprintf("Total: %d", sum(!is.na(x)))
    }
    r
}
```

![image](https://user-images.githubusercontent.com/17572252/122774211-ff87dd00-d276-11eb-978b-72939f7aa543.png)

**Comment by gueyenono** [comment]
This is very well noted. Thank you.

**Comment by boniale** [comment]
@benjaminrich, this is fantastic. You have been very quick in providing a very nice solution. Thank you.
