### ISSUE TITLE
Custom render.continuous returns strange results

### ISSUE THREAD

**Issue by jmb01** [benjaminrich/table1#59]
Hi @benjaminrich, 

I recently posted [this question on stackoverflow ](https://stackoverflow.com/questions/68217665/custom-render-continuous-in-table1table1) and, having not received any answers yet, will reproduce it here in case you have time for it.

My goal is to be able to use a custom `render.continuous` for ordinal variables that summarizes the mean/median as well as the frequency of each unique value. I have written `render.ordinal()` for this purpose, but there is clearly something I don't understand about how to results come to be displayed in the table as I am seeing misalignment and recycling of output. 

```
render.ordinal <- function(x, value.prefix = "= ") {
  
  require(scales)
  
  N <- sum(!is.na(x))
  nmiss <- sum(is.na(x))
  mean <- mean(x, na.rm = TRUE)
  median <- median(x, na.rm = TRUE)
  freqs <- table(factor(x))
  pcts <- freqs / N
  freqs_formatted <- paste0(freqs, " (", percent(as.numeric(pcts)), ")")
  names(freqs_formatted) <- paste0(value.prefix, names(freqs), ", n (%)")
  
  out <- c("",
           "N" = N,
           "Mean / Median" = paste0(sprintf("%.2f", mean), " / ", sprintf("%.2f", median)),
           freqs_formatted)
  
  out
  
}

```

Here is a reproducible example that should demonstrate the issue.
```

# cross-tabulation of transmission type by number of carbs.
with(mtcars, {table(carb, ifelse(am == 1, "Auto.", "Std."))})
#carb Auto. Std.
 #  1     4    3
 #  2     4    6
 #  3     0    3
 #  4     3    7
 #  6     1    0
 #  8     1    0

# call table1() with custom render.continuous, see HTML output for incorrect results
library(table1)
table1(~ gear + carb + cyl | ifelse(am == 1, "Auto.", "Std."), 
       data = mtcars, 
       render.continuous = render.ordinal)

#Warning messages:
#1: In (function (..., deparse.level = 1)  :
# number of rows of result is not a multiple of vector length (arg 1)
#2: In (function (..., deparse.level = 1)  :
# number of rows of result is not a multiple of vector length (arg 1)
```

Is there any way that `render.ordinal()` can be adapted to overcome this issue? I know I could create separate factor and numeric versions of these variables and include them separately, but I would prefer a more compact output in a single table row. 

Thank you for any help and for the excellent package!

**Comment by benjaminrich** [comment]
The problem is knowing what the unique values of each variable are, so that the `render` function can return a vector of the same length each time even if a particular stratum does not contain a particular value. This is handles automatically for `factor`s because of the `levels` property.

One solution would be to treat the variables as categorical instead of continuous:

```r
render.ordinal <- function(x, value.prefix = "= ") {
  
  require(scales)

  # x is a factor
  N <- sum(!is.na(x))
  freqs <- table(x)
  pcts <- freqs / N
  freqs_formatted <- paste0(freqs, " (", percent(as.numeric(pcts)), ")")
  names(freqs_formatted) <- paste0(value.prefix, names(freqs), ", n (%)")
  
  # Now, convert to numeric
  x <- as.numeric(as.character(x))
  nmiss <- sum(is.na(x))
  mean <- mean(x, na.rm = TRUE)
  median <- median(x, na.rm = TRUE)

  out <- c("",
           "N" = N,
           "Mean / Median" = paste0(sprintf("%.2f", mean), " / ", sprintf("%.2f", median)),
           freqs_formatted)
  
  out
}


table1(~ factor(gear) + factor(carb) + factor(cyl) | ifelse(am == 1, "Auto.", "Std."), 
       data = mtcars, 
       render.categorical = render.ordinal)
```
![image](https://user-images.githubusercontent.com/17572252/125098225-d94ea380-e0a4-11eb-8db2-36476dd98183.png)


Another approach is to extract the unique values from the whole dataset inside the render function. For this, I will use the `render` argument instead of `render.continuous` so I get the name of the variable. I will also pass the dataset as `data2`, because `data` is not passed to the `render` function.

```r
render.ordinal <- function(x, name, data2, ..., value.prefix = "= ") {

  require(scales)
  
  lvls <- levels(factor(data2[[name]]))  # Contains all unique values
  
  N <- sum(!is.na(x))
  nmiss <- sum(is.na(x))
  mean <- mean(x, na.rm = TRUE)
  median <- median(x, na.rm = TRUE)
  freqs <- table(factor(x, levels=lvls))
  pcts <- freqs / N
  freqs_formatted <- paste0(freqs, " (", percent(as.numeric(pcts)), ")")
  names(freqs_formatted) <- paste0(value.prefix, names(freqs), ", n (%)")
  
  out <- c("",
           "N" = N,
           "Mean / Median" = paste0(sprintf("%.2f", mean), " / ", sprintf("%.2f", median)),
           freqs_formatted)

  out
  
}

table1(~ gear + carb + cyl | ifelse(am == 1, "Auto.", "Std."), 
       data = mtcars, data2 = mtcars,
       render = render.ordinal)
```
The result is the same.

**Comment by jmb01** [comment]
Thanks @benjaminrich, this is solved!
