### ISSUE TITLE
Mean, median, min, max not working consistently

### ISSUE THREAD

**Issue by samuelsaari** [benjaminrich/table1#61]
table1 works great with example data,but unfortunately not with my research data so cannot produce a reprex.

Here is an example:
`table1(~ yrbirth | c, data = desc)`

![image](https://user-images.githubusercontent.com/49607659/128725976-636dddf2-4b93-46b5-9619-34721fca4b63.png)

Which is clearly not the case, when calculated with..

```
desc %>% group_by(c) %>% 
  summarise_at(vars(yrbirth), list(Min = min, Mean = mean, Median=median, Max = max, Sd = sd))

# A tibble: 6 x 6
  c           Min  Mean Median       Max    Sd
  <fct> <dbl+lbl> <dbl>  <dbl> <dbl+lbl> <dbl>
1 1          1945 1950.   1950      1957  3.61
2 2          1945 1951.   1951      1957  3.65
3 3          1945 1951.   1951      1957  3.56
4 4          1945 1951.   1951      1957  3.72
5 5          1945 1951.   1951      1957  3.62
6 6          1945 1951.   1951      1957  3.67
```

This could be hard to debug, but just letting you know that at least in my case it does not work. Have tried to change the dataframe & yrbirth column but no luck.

**Comment by benjaminrich** [comment]
You need to increase the number of significant digits. The default is 3, but for years you need at least 4. See #24.

**Comment by samuelsaari** [comment]
Thank you Benjamin for your quick answer and handy package!
