### ISSUE TITLE
How to export the table to an excel file? I've just been screenshoting so far. Thanks! 

### ISSUE THREAD

**Issue by elliewky** [benjaminrich/table1#66]

**Comment by benjaminrich** [comment]
It should work with copy-paste if you can open the HTML file in Chrome (the new Edge which is based on Chrome also works; it used to work directly from RStudio, but that doesn't seem to be working anymore; firefox also doesn't work great). Some options are:

1. From the RStudio Viewer pane, click 'Show in new window' - it will open in your default browser.
2. Use 'Compile Report' (ctrl-shift-k) to 'knit' the R script, and open the resulting HTML file in Chrome (you can click 'Open in Browser' if Chrome is your default browser).
3. Save the HTML file, and open it.
4. Don't use RStudio 

Here is a screenshot of the result:

![image](https://user-images.githubusercontent.com/17572252/146380005-a95224e0-8d0a-4c97-bb59-5505a57196d2.png)

**Comment by elliewky** [comment]
Yes . This works! Thank you!
