### ISSUE TITLE
Weighted frequencies?

### ISSUE THREAD

**Issue by jgaf151** [benjaminrich/table1#67]
Is there a way to output weighted frequencies? Been trying to look into it to try to edit the table1 function but I have no idea where to start. Any help or suggestions would be appreciated.

**Comment by benjaminrich** [comment]
Can you post a minimal working example of what you want? Some data, and the expected output?

**Comment by jgaf151** [comment]
Not sure where to start, but using other packages to kind of explain what I want. I love how table1 outputs html tables that can be easily stratified by categorical variables. I am currently working on a dataset that has 5 different cohorts and I want to have the weighted frqs instead of the sample frqs, I do have a weight variable that I can use to calculate the weights using other packages, but can't output a long table1 with all the variables of interest as your package does.

Here is an example using some pewresearch sample dataset:

`devtools::install_github("pewresearch/pewmethods", build_vignettes = TRUE)

dat <- pewmethods::dec13_excerpt

sjmisc::frq(dat$racethn2) #unweighted frqs
sjmisc::frq(dat$racethn2, weights = dat$weight, out = "viewer") #weighted frq outputting to html table`

Added image of the table sjmisc produces, ideally I would be interested in getting the "frq" and "valid.prc" columns to show as they are presented when calling table1. Note that this only a single variable, I could manually do each separate variable and then combine into a similar looking table1 output in Excel. 

![weightedtable](https://user-images.githubusercontent.com/16786565/146392148-997700dc-ca57-4257-8f9d-3fd20b842d2e.PNG)

A crosstab might be more apt as an example, using the same dataset above:

`sjPlot::sjt.xtab(dat$racethn2, dat$sex, show.col.prc = T, weight.by = dat$weight, show.summary = F)`

Ideally, it would include more than one crossing variable at a time like table1 does but using the calculated weighted frq and prc.

![weightedxtab](https://user-images.githubusercontent.com/16786565/146393125-6bfa50fd-b435-4822-a632-cbe0fc2f11d5.PNG)

**Comment by benjaminrich** [comment]
Thanks for providing this example, and for bringing up this issue. Indeed, it's not possible to do this cleanly with `table1` currently. I may (if I find time) try to add this functionality in a later version. For now, the best I can offer is a hack. Using your example:

```
# Create a 'fake' data.frame with the same column names and labels
# as the original but containing only indices
indices_preserve_label <- function(x) {
    setLabel(1:length(x), label(x))
}
dat2 <- as.data.frame(lapply(dat, indices_preserve_label))

# A custom render function what expects indices and calculates the weighted frequencies
rndr <- function(x, name, ..., dat1=NULL, weight=NULL) {
    i <- x
    w <- weight[i]
    x <- dat1[[name]][i]
    if (is.factor(x)) {
        c("", sapply(levels(x), function(z) {
            sprintf("%s (%s%%)",
                round(sum(w*(x==z))),
                round_pad(100*sum(w*(x==z))/sum(w), 1))
        }))
    } else {
        render.default(x, name, ...)
    }
}

# We also need a custom render function for the column headings to get the right N
rndr.strat <- function(label, ...) {
    n <- sapply(label, function(z) round(sum(dat$weight*(dat$sex==z))))
    n["overall"] <- sum(n[names(n) != "overall"])
    render.strat.default(label, n)
}

table1(~ racethn2 | dat$sex, data=dat2, render=rndr, dat1=dat, weight=dat$weight, render.strat=rndr.strat)
```

Result:

![image](https://user-images.githubusercontent.com/17572252/146426344-e58b00dc-f1a0-43b1-9df2-3451f9aa2ef5.png)

**Comment by jgaf151** [comment]
Awesome, will try this out. Thank you so much! Your package has saved me countless hours of editing outputs.

**Comment by benjaminrich** [comment]
Great. I will close the issue now. Like I said, it might be nice functionality to include in the future, but I will need to think about it.
