### ISSUE TITLE
How to round to a number of decimal places, rather than to significant digits?

### ISSUE THREAD

**Issue by alexpate30** [benjaminrich/table1#68]
I have been using the following code the manually choose the output for continuous variables:

my.render.cont <- function(x) {
  with(stats.apply.rounding(stats.default(round(x, 2)), digits = 5), c("", 
       "Mean (SD)"=sprintf("%s (&plusmn; %s)", MEAN, SD)))
}

and option

render.cont = my.render.cont

However, I would like to round the descriptive statistics by a number of decimal places, rather than significant figures. Is it possible to do this within table1?

As far as I can tell: https://www.rdocumentation.org/packages/table1/versions/1.4.2/topics/stats.apply.rounding this is not possible?

I have been playing around with the example given on the documentation page and have been unable to make it work:

x <- round(exp(rnorm(100, 1, 1)), 6)
stats.default(x)
stats.apply.rounding(stats.default(x), digits=3)
stats.apply.rounding(stats.default(round(x, 1)), digits=3)

Many thanks if able to help.

**Comment by benjaminrich** [comment]
Sure, it's possible, and there are a few different ways to go about it. You could try this simple example:
```r
dat <- data.frame(x=2^(-3:10))

my.render.cont <- function (x, ...) {
    with(lapply(stats.default(x, ...), round_pad, ...), c("", 
        `Mean (SD)` = sprintf("%s (%s)", MEAN, SD), `Median [Min, Max]` = sprintf("%s [%s, %s]", 
            MEDIAN, MIN, MAX)))
}

table1(~ x, data=dat, render.continuous=my.render.cont, digits=1)
table1(~ x, data=dat, render.continuous=my.render.cont, digits=2)
table1(~ x, data=dat, render.continuous=my.render.cont, digits=3)
```

**Comment by benjaminrich** [comment]
Hi @alexpate30. Can I close this issue?

**Comment by benjaminrich** [comment]
Closing this now, since no response from OP.
