### ISSUE TITLE
preview mode not work

### ISSUE THREAD

**Issue by hdeng88** [benjaminrich/table1#7]
the html table will be shown in viewer mode not inline mode. works fine in knit html but not notebook.

**Comment by benjaminrich** [comment]
I don't really use notebook, is that RStudio specific, or a general problem?

**Comment by hdeng88** [comment]
I think it is Rstudio specific. but I have seen this happened to other packages but fixed afterwards quickly so I guess it is not a difficult fix. 

Also could you provide a default option to output median [Q1,Q3]? I think this is more academically standard from a reviewer standpoint. If there are multiple variables needed to be presented in different format, how could I format them differently? say age for median[Q1,Q3] but weight for mean (SD).

**Comment by benjaminrich** [comment]
I will try to look into it, but I don't know when. If you can provide information on how notebook works in RStudio and how to feed it HTML that will be helpful.

As to your other question, you can. Here is an example:

~~~
library(table1)

dat <- data.frame(Age=runif(100, 40, 65), Weight=rnorm(100, 75, 10))

rndr <- function(x, name, ...) {
    if (name == "Weight") {
        parse.abbrev.render.code(c("", "Mean (SD)"))(x)
    } else {
        parse.abbrev.render.code(c("", "Median [Q1, Q3]" = "Median [Q25, Q75])"))(x)
    }
}
table1(~ Age + Weight, data=dat, render=rndr)
~~~

**Comment by benjaminrich** [comment]
This is working now in pull request #9. Do you want to test it?

**Comment by hdeng88** [comment]
sure. just checked. Somehow it did not work the way as we expected. Could u
double check?

Hao

**Comment by benjaminrich** [comment]
Are you using the right branch? The change has not been merged into the master branch yet, so you want to be installing with:

```r
devtools::install_github("benjaminrich/table1#9")
```

**Comment by hdeng88** [comment]
Hi Benjamin,

I had some trouble using the "

devtools::install_github("benjaminrich/table1#9")

"
command.

It says that:

> devtools::install_github("benjaminrich/table1#9")
Downloading GitHub repo benjaminrich/table1@issue-#7
from URL https://api.github.com/repos/benjaminrich/table1/zipball/issue-#7
Installation failed: 404: Not Found
 (404)

I got an error message after installing table1 from github.

Error: package or namespace load failed for ‘table1’ in get(Info[i, 1],
envir = env):
 lazy-load database
'/Library/Frameworks/R.framework/Versions/3.4/Resources/library/Formula/R/Formula.rdb'
is corrupt
In addition: Warning message:
In get(Info[i, 1], envir = env) : internal error -3 in R_decompress1

**Comment by benjaminrich** [comment]
OK, my bad, it did not work as I expected. Try this instead:

```r
devtools::install_github("benjaminrich/table1", ref="issue-%237")
```

**Comment by hdeng88** [comment]
sorry still not working

**Comment by benjaminrich** [comment]
Which one is still not working, the installation, or the preview in RStudio?

**Comment by hdeng88** [comment]
the preview. I have tried using result. = asis but it did Not work as well.

**Comment by benjaminrich** [comment]
It is working for me. Here's a screenshot:

![screenshot_issue7](https://user-images.githubusercontent.com/17572252/41723282-a74a1390-7538-11e8-9a9e-2c2a7f27ca89.png)

**Comment by hdeng88** [comment]
I think it is related to ur rstudio or packages version? Any development
version of packages you are using

**Comment by benjaminrich** [comment]
Here is the output of `sessionInfo()`:

~~~
> sessionInfo()
R version 3.5.0 (2018-04-23)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] table1_1.1    rmarkdown_1.9

loaded via a namespace (and not attached):
 [1] compiler_3.5.0  backports_1.1.2 magrittr_1.5    rprojroot_1.3-2
 [5] tools_3.5.0     htmltools_0.3.6 Rcpp_0.12.17    stringi_1.1.7  
 [9] knitr_1.20      Formula_1.2-3   stringr_1.3.1   digest_0.6.15  
[13] evaluate_0.10.1
~~~

Does that help?

**Comment by benjaminrich** [comment]
And my RStudio version is 1.1.453.

**Comment by hdeng88** [comment]
I will switch to Rstudio newest version to see if this is the key.

**Comment by hdeng88** [comment]
Done. It is because of the version of rstudio

**Comment by benjaminrich** [comment]
Excellent. Then I am closing the issue. Thanks.

**Comment by hdeng88** [comment]
sounds good! Great job!
