### ISSUE TITLE
Adding ANOVA-derived p-values?

### ISSUE THREAD

**Issue by navonacalarco** [benjaminrich/table1#70]
Hi Benjamin,

Thank you so much for this great package. 

I would like to add p-values deriving from ANOVA to a table1 table. I can see in your documentation that you have a clear demonstration of how to add p-values from t.test/chisq.test ("Extra columns").

I am struggling to extend this example to ANOVA. I thought I might be able to modify relevant code to something like `aov(y ~ g)`. This 'works' in the sense that no error is produced, but it seems that the p-values generated are incorrect when I compare them to p-values I've calculated via ANOVA in R. 

Additionally, with reproducible data, someone has asked the same question on [StackOverflow](https://stackoverflow.com/questions/67711459/anova-p-value-column-in-table1-package-r). They have provided a solution to their own question, but to me, it looks like they too might be deriving incorrect values. 

Could you please advise about how to modify the calculations of y and/or g within the example p-value function to correctly deal with >3 groups?

Thank you!

**Comment by navonacalarco** [comment]
Ah, I'm sorry, I've got it -- everything is well, my error was including the 'Total' column erroneously, over which the statistics were also computed. Thank you!

**Comment by benjaminrich** [comment]
I see. Great that you were able to find the solution.
