### ISSUE TITLE
How to include breakdown for weighted and unweighted counts

### ISSUE THREAD

**Issue by RosalynLP** [benjaminrich/table1#71]
Hi, this seems like a really useful resource so thank you! I'm trying to produce a table where each column is broken down into two to include an unweighted count of the data (the default in this package) and also a weighted count. I am trying to do this using the extra.col argument in table1 using dplyr::count() with the wt argument containing the weights, but I can't get the syntax for this to work properly.

**Comment by RosalynLP** [comment]
Just to note that I think https://github.com/benjaminrich/table1/issues/67 might answer my question.

**Comment by benjaminrich** [comment]
Yes, I was going to suggest to look at #67.

But based on what you said ("where each column is broken down into two ..."), I can also propose a solution based on a completely different package (which I also wrote). I will use the same data from the previous example to demonstrate.

```r
dat <- pewmethods::dec13_excerpt

rndr <- function(x, ...) {
    c(Unweighted=length(x), Weighted=round(sum(x)))
}

ttt(weight ~ racethn2 | sex, data=dat, render=rndr, expand.along="columns")
```
![image](https://user-images.githubusercontent.com/17572252/149521941-c6c4f8d6-7fd9-4ec4-b350-b1bba991fa66.png)

I don't know if this is more what you are after?

**Comment by RosalynLP** [comment]
Thanks this is ideal - exactly what I was looking for! I really appreciate the quick and comprehensive reply :)
