### ISSUE TITLE
P-value calculation includes the overall column when such is used?

### ISSUE THREAD

**Issue by Beduiz** [benjaminrich/table1#72]
Hi Benjamin!

Thank you for your previous support and replies. Sorry that I was late to reply to the last suggestion you gave me. 

However I've found a new error that is that when adding "overall = T", that column is also used by the significance tests, which renders erroneuous results (or at least the p-values change depending on wether or not overall is T or F). My current solution is to first render the table with total and then without, and then manually copy the correct p-values from the latter table to the first one, but this of course is a little bit tedious. Is there a way to program the table so that the overall column is not included in the significance tests?

Best regards
Eric

**Comment by benjaminrich** [comment]
Hi Eric,

That is correct, as I mentioned in #69. When you include the "overall" column, it gets treated like any other column inside the `pvalue()` function. So for the calculation to be correct, this column should be removed from consideration. You can do so with a simple line at the start of the `pvalue()` function:

```r
pvalue <- function(x, name, ...) {

    # Remove the "overall" column
    x <- x[names(x) != "overall"]
    
    ... # the function continues as before
}
```

**Comment by Beduiz** [comment]
Thank you Benjamin. It works perfectly. 
Best regards
Eric
