### ISSUE TITLE
Format table1 "Median [Min, Max]"

### ISSUE THREAD

**Issue by xinyueandtianliangle** [benjaminrich/table1#73]
Dear developer of table1 package,

I'd like to format "Median [Min, Max]" for numeric variables. 
I'd like it to be "Median (Min, Max)" with two decimals. 
I've tried several hours and cannot make it out. 
If you've time, could you please give some instructions? 
Thanks.
 Best,
Yun

**Comment by benjaminrich** [comment]
Hi. Here is an example of what you want:

```r
library(table1)

set.seed(123)

d <- data.frame(x=rnorm(20, 70, 12), y=seq(5, 234, len=20))

table1(~ x + y, data=d, render.continuous=c("", "Median (Min, Max)"),
    rounding.fn=round_pad, digits=2)
```
![image](https://user-images.githubusercontent.com/17572252/152587167-4ee1cb21-e83c-4efd-a771-c05632778bbe.png)

**Comment by xinyueandtianliangle** [comment]
Dear Benjamin,


Thanks for reply. But if there are more than 2 decimals, for example, 0.00753 is shown as 0.0075.
Could it be shown as 0.01?


Best regards,
Yun













At 2022-02-05 02:59:20, "Benjamin Rich" ***@***.***> wrote:

Hi. Here is an example of what you want:

library(table1)

set.seed(123)

d<-data.frame(x=rnorm(20, 70, 12), y=seq(5, 234, len=20))

table1(~x+y, data=d, render.continuous=c("", "Median (Min, Max)"),
    rounding.fn=round_pad, digits=2)

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by benjaminrich** [comment]
Hi Yun,

Maybe you didn't read my example correctly. You have to make sure to include `rounding.fn=round_pad`. If you do, you should get the result you want. Here is an updated version of the example with `z =0.00753` for all rows, and it is indeed shown as 0.01, as you want.

```r
d <- data.frame(x=rnorm(20, 70, 12), y=seq(5, 234, len=20), z=rep(0.00753, 20))

table1(~ x + y + z, data=d, render.continuous=c("", "Median (Min, Max)"),
    rounding.fn=round_pad, digits=2)
``` 

![image](https://user-images.githubusercontent.com/17572252/152798401-ab6082ba-357e-476e-8d75-a10cf4e3fca8.png)

**Comment by xinyueandtianliangle** [comment]
Hi Benjamin,


Thanks so much. It's solved. I ran your example but failed the first time. Then I updated the package version and it works. 


Best regards,
Yun













At 2022-02-07 21:41:17, "Benjamin Rich" ***@***.***> wrote:

Hi Yun,

Maybe you didn't read my example correctly. You have to make sure to include rounding.fn=round_pad. If you do, you should get the result you want. Here is an updated version of the example with z =0.00753 for all rows, and it is indeed shown as 0.01, as you want.

d<-data.frame(x=rnorm(20, 70, 12), y=seq(5, 234, len=20), z=rep(0.00753, 20))

table1(~x+y+z, data=d, render.continuous=c("", "Median (Min, Max)"),
    rounding.fn=round_pad, digits=2)

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by benjaminrich** [comment]
Great. Indeed, it's always important to use the latest version. I will close this issue now.

**Comment by samuelsaari** [comment]
Is there a way to get rid off the blank space between x,y,z and Median? There seems to be an extra line break.

**Comment by benjaminrich** [comment]
Hi @samuelsaari. You are right, thanks for pointing this out. The better way would have been:

```r
table1(~ x + y + z, data=d, render.continuous=c("Median (Min, Max)"="Median (Min, Max)"),
    rounding.fn=round_pad, digits=2)
``` 

Alternatively, if you want a much more compact table you can remove the repetitive "Median (Min, Max)"  like this:

```r
table1(~ x + y + z, data=d, render.continuous=c("Median (Min, Max)"),
    rounding.fn=round_pad, digits=2, footnote="Note: Cells contain Median (Min, Max)")
```
