### ISSUE TITLE
Missing column & proportionn

### ISSUE THREAD

**Issue by PierreH94** [benjaminrich/table1#75]
Hello Benjamin and thank you very much for this amazing package. 
I've been using it for several weeks now for my MD work and thanks to all your answers I've been able to do almost everything I want. 

I've got two inquiries left, maybe you could help me ? 

The first one is about missing values. I'm working on a database with a bunch off missing values and it is an important information to display, but my tables are pretty long and adding it as a new row each time makes it pretty dense.  
I'm actually using this rndr function : 

rndr <- function(x, name, ...) {
    cont <- ifelse(name %in% vars.normal, "Mean (SD)", "Median (Q1 - Q3)")
    y <- render.default(x, name, render.continuous=cont, ...)
    if (is.logical(x)) {
        y[2] 
    }  
    else {
        y
    }
}

I've been able for numerical values to add it like that :     
cont <- ifelse(name %in% vars.normal, "Mean (SD) **/ NMISS**", "Median (Q1 - Q3) **/ NMISS**")

But for non numerical values, I must admit i don't have a clue where to start and if it's possible to add it in the function ? 
And for NMISS, the result is display with 1 or 2 decimals, do you know if it's possible to show 0 decimals ?  

II/ The second one is about %. 
I would like to know if there is anyway to calculate percentage only for a certain subset for some variables and for all values ? 

Using the melanoma example, i'd like to know if it's possible to display something like this : 

table1 (~ age + thickness | sex, data = melanoma)

Where for the age variable i would like to get the mean for all patients, but for the thickness variable i would like to get the mean only for patients where ulcer == 1 ? 

So it would display something like that for the age
<img width="508" alt="image" src="https://user-images.githubusercontent.com/99976557/154710922-8afc6c7b-0ea8-4de9-b91c-b2f621c32ae2.png">

And something like that for the thickness (only the right column)
<img width="652" alt="image" src="https://user-images.githubusercontent.com/99976557/154711229-40cc6dba-fc9e-4e08-9e3c-ea1624bf3b6a.png">

All of that in the same table. 

Hope i'm being clear and again thank you very much for your hardwork 

Pierre

**Comment by PierreH94** [comment]
Hello Benjamin,

Thank you very much for your reactivity and for the NMISS part, just tried it out and it works perfectly !

**Comment by benjaminrich** [comment]
Hi Pierre,

Yes, I was going to say that I pushed some small changes to remove the decimals from NMISS. You could use the same approach for for binary variables, but I'm not sure where you would want display the number missing for categorical variables with more than 2 categories. Here's an example:

```r
# Generate some simulated data
set.seed(567)
n <- 123
d <- data.frame(
    A = rnorm(n, 70, 15),
    B = runif(n, 10, 99),
    C = runif(n) > 0.5)

# Add some missing values
d$A[sample(1:n, 5)] <- NA
d$B[sample(1:n, 7)] <- NA
d$C[sample(1:n, 8)] <- NA

vars.normal <- "A"

label(d$A) <- "A, Mean (SD) / #missing"
label(d$B) <- "B, Median (Q1 - Q3) / #missing"
label(d$C) <- "C, n (%) / #missing"

rndr <- function(x, name, ...) {
    cont <- ifelse(name %in% vars.normal, "Mean (SD) / NMISS", "Median (Q1 - Q3) / NMISS")
    categ <- "FREQ (PCTnoNA%) / NMISS"
    y <- render.default(x, name, render.continuous=cont, render.categorical=categ, ...)
    if (is.logical(x)) {
        y[2]
    } else {
        y
    }
}

table1(~ A + B + C, data=d, render=rndr, render.missing=NULL)
```
![image](https://user-images.githubusercontent.com/17572252/154807169-5bc192a2-98f5-4898-9937-132ee142dc54.png)

For your second issue, there are some tricks you could use to get what you want. The simplest is to create a new variable that has `NA` for the subjects that you don't want to include in the calculation (just make sure not to show them as true missing values). For the example you gave, it could be something like this:

```r
library(boot)
library(table1)

melanoma2 <- melanoma

melanoma2$thickness.ulcer <- with(melanoma2, ifelse(ulcer==1, thickness, NA))

label(melanoma2$age)             <- "Age (years)"
label(melanoma2$thickness.ulcer) <- "Thickness, only for patients with ulceration (mm)"

table1(~ age + thickness.ulcer | sex, data=melanoma2, render.missing=NULL)
```
![image](https://user-images.githubusercontent.com/17572252/154807278-0afa09e3-3ff9-4082-9f50-5b2765b73a52.png)

If that doesn't work for your case (i.e. because you have true missing values, or need to display things differently) then there might be other approaches that would work.

**Comment by PierreH94** [comment]
Thanks ! 

Indeed adding it as missing values and doing the calculation while excluding NA was my first thought but I do have some NA for these variables. 
For now I've been doing it by creating a new df with subset and merging them in excel after generating it but I do loose the formatting that your package provides ! 
I'd be glad to hear about your other approach if you have any idea!

**Comment by benjaminrich** [comment]
You could always combine both variables into a `character` and then separate them out again in the render function, like this:

```r
melanoma2$ulcer.thickness <- with(melanoma2, paste(ulcer, thickness, sep=":"))

rndr <- function(x, name, ...) {
    if (name == "ulcer.thickness") {
        y <- read.table(text=paste(x, collapse="\n"), sep=":")
        x <- y[[2]][y[[1]] == 1]
    }
    render.default(x, name, ...)
}

table1(~ age + ulcer.thickness | sex, data=melanoma2, render.missing=NULL, render=rndr)
```

Another alternative would be to pass the indices of the rows instead of the values, and then extract the values from the full `data.frame`, like this:

```r
melanoma2$thickness.indices <- 1:nrow(melanoma2)

rndr <- function(x, name, ..., mydata) {
    if (name == "thickness.indices") {
        x <- subset(mydata[x,], ulcer==1)$thickness
    }
    render.default(x, name, ...)
}

table1(~ age + thickness.indices | sex, data=melanoma2, render.missing=NULL, render=rndr, mydata=melanoma2)
```

**Comment by benjaminrich** [comment]
A small tweak will do it. Here is a complete example (I reformatted your code a bit):

```r
library(boot)
library(table1)

melanoma2 <- melanoma

# Add some missing values
melanoma2$age[sample(1:nrow(melanoma2), 11)] <- NA
melanoma2$ulcer[sample(1:nrow(melanoma2), 3)] <- NA
melanoma2$thickness[sample(1:nrow(melanoma2), 5)] <- NA

melanoma2$sex.binary <- with(melanoma2, sex == 1)
melanoma2$sex.factor <- with(melanoma2, factor(sex, labels=c("Female", "Male")))

# Combine ulcer and thickness
melanoma2$ulcer.thickness <- with(melanoma2, paste(ulcer, thickness, sep=":"))

vars.normal <- c("ulcer.thickness")
vars.dep    <- c("ulcer.thickness")

rndr <- function(x, name, ...) {

    if (name %in% vars.dep) {
        z <- read.table(text=paste(x, collapse="\n"), sep=":")
        x <- z[[2]][!is.na(z[1]) & z[[1]] == 1]
    } 

    if (is.numeric(x)) {
        cont <- ifelse(name %in% vars.normal, "Mean ± SD - NMISS", "Median (Q1 - Q3) - NMISS")
        render.default(x, name, render.continuous=cont, ...)
    } else if (is.logical(x)) {
        y <- render.default(x, name, render.categorical="FREQ (PCT%) - NMISS", ...)
        y[2]
    }
    else {
        render.default(x, name, ...)
    }
}

label(melanoma2$age)             <- "Age (years), Mean ± SD - #missing"
label(melanoma2$ulcer.thickness) <- "Thickness, only for patients with ulceration (mm), Median (Q1 - Q3) - #missing"
label(melanoma2$sex.binary)      <- "Male, n (%) - #missing"
label(melanoma2$sex.factor)      <- "Sex"

table1(~ age + ulcer.thickness + sex.binary + sex.factor | sex.factor, data=melanoma2, render=rndr)
```
![image](https://user-images.githubusercontent.com/17572252/154986078-96e2fab3-526f-4da3-9ba4-a90abd4a705e.png)

**Comment by PierreH94** [comment]
It works perfectly well, thank you for your hard work !
The result is amazing !

**Comment by benjaminrich** [comment]
Great!
