### ISSUE TITLE
Can't use the dots notation to pass in arguments to extra.col function.

### ISSUE THREAD

**Issue by Dekermanjian** [benjaminrich/table1#76]
When I use the ... notation to pass in arguments to the function used in the extra.cols argument I lose the parameter x, and name. 

For example

```
pval <- function(x, name, ...) {
args = list(...)
etc... 
}
```

when using 
```
table1(
    extra.cols = list(`pval` = pval(arg1=arg1, arg2=arg2) )
)
```

x and name are no longer passed into the function.

**Comment by benjaminrich** [comment]
I'm not really sure what you are trying to do. Can you give a real example, and explain what arg1 and arg2 are?

**Comment by Dekermanjian** [comment]
Sure, I am calling your table1 function using a wrapper I built to stream line some rendering properties. I am trying to pass in variables to the p_value function [here](https://github.com/CIDA-CSPH/CIDAtools/blob/master/R/table1_pvalue.R) from my wrapper function to the table1 function through the dots notation. When I successfully pass the arguments (validated by printing them in the p_value function, I lose the default x, name functions that the table1 function passes to the extra.col argument) Right now, I have to pull the variables I want using mget by pointing to the correct environment, which is not clean (lines 16 and 17).

**Comment by benjaminrich** [comment]
I see. So, you want to be able to pass arguments into the `pval` function so that it does different things. You can do it like this:

```r
pvalue <- function(x, name, ..., include_total=F, nonParametricVars=character(0)) {
    ...
}

table1(...,
    extra.cols=list(`<i>p</i>-value`=pvalue), 
    include_total=include_total, nonParametricVars=nonParametricVars)
```

I think that will work (but haven't tested it). Let me know!

**Comment by Dekermanjian** [comment]
Thank you for your help, this seems to work but only when I am not using the arguments like render.missing or render.continuous. Otherwise, I am getting an unused arguments error. I think what is happening is that the arguments include_total and nonParametricVars are also being passed into the render.* functions and causing an unused arguments error.

**Comment by benjaminrich** [comment]
That is exactly what is happening. The easy way to deal with this is to allow those functions to accept any arguments by adding `...` to their signatures. So if you have this:

```r
myrendercont <- function(x) { ... }
```
you replace it with

```r
myrendercont <- function(x, ...) { ... }
```
and the same for the other functions.

**Comment by Dekermanjian** [comment]
Thank you, that solved my issue. I appreciate all of your help.

**Comment by benjaminrich** [comment]
No problem. But in future, it is best to post a working example, then you will get help more quickly.
