### ISSUE TITLE
Table1 percentages not adding to 100

### ISSUE THREAD

**Issue by daisyburr** [benjaminrich/table1#78]
The percentages in my table1 do not add up to 100 for each category column:

 https://docs.google.com/document/d/1MoZdf3bI0pdW8nlbhee92WzQdzN_LiUaORRYrwbS17E/edit?usp=sharing

**Comment by daisyburr** [comment]
<img width="697" alt="Screen Shot 2022-03-22 at 11 58 34 AM" src="https://user-images.githubusercontent.com/26144925/159523693-34e5a0a6-bad7-4d3c-94b5-e40f0484f5f7.png">

**Comment by benjaminrich** [comment]
It seems like you have missing data, is that correct? If you don't want the missing values to be considered in the percentage calculation, try adding this: `render.categorical="FREQ (PCTnoNA%)"`

**Comment by daisyburr** [comment]
That fixed it--thanks!
