### ISSUE TITLE
add additional quantile stats e.g q1/3 and q2/3

### ISSUE THREAD

**Issue by smouksassi** [benjaminrich/table1#8]
it is common that we need the 1/3 and 2/3 quantiles ( dividing the data into tertiles) so one would like to know the cutoffs for the tertiles, quartiles

**Comment by benjaminrich** [comment]
Quartiles can be accesses with Median and Q1, Q3 or q25, q75 in stats.default (with pull request #9). Would you be happy with T1, T2 as notation for tertiles?

**Comment by smouksassi** [comment]
T1 and T2 seams reasonable  thank you. I was thinking along eq.cut capabilities where we might have special version of these stats that would exclude the placebo zeros. it is like you want a tabular version of what your represent on exposure response plots.

**Comment by benjaminrich** [comment]
In that case, it seems that what you are asking for is not a change to stats.default, but rather a nice way to create a stratification factor from a continuous variable, like this:

```r
table1(~ x1 + x2 + x3 | eqcut(x4, 3), data=dat)
```

**Comment by benjaminrich** [comment]
Added in pull request #11.
