### ISSUE TITLE
t1kable with custom renderers 

### ISSUE THREAD

**Issue by samuelsaari** [benjaminrich/table1#82]
Thank you Benjamin for a great project.

I am trying to convert a table1 object to latex via kable. It seems that this is not possible when using custom renderers:

When for example following the [vignette](https://benjaminrich.github.io/table1/vignettes/table1-examples.html), after we specify the table1 object with custom rendes..

```
rendered_table1_object <- table1(strata, labels, groupspan=c(1, 1, 2),
       render.continuous=my.render.cont, render.categorical=my.render.cat)
```
...and run the t1kable command...

```
t1kable(rendered_table1_object ,format='latex')
#Error in rbind(deparse.level, ...) : 
# numbers of columns of arguments do not match
```
..it produces an error which it doesn't produce without the renderers.

The full MVE can be found in [this gist](https://gist.github.com/samuelsaari/495239cdcf4ab70dbcadc02d69d4f2c5).

**Comment by benjaminrich** [comment]
Thanks for pointing that out. I have pushed as fix. If you can, please install the latest version from GitHub and try it out. It should be working as expected now.

**Comment by samuelsaari** [comment]
Unfortunately no luck. Is table1_1.4.2 the most recent version?

Reinstalled R, restarted computer and downloaded the package from github. Updated MVE [in the gist](https://gist.github.com/samuelsaari/495239cdcf4ab70dbcadc02d69d4f2c5). (same thing on a server with the code I am actually working on)

**Comment by benjaminrich** [comment]
Did you install it like this?
```r
require(devtools)
devtools::install_github("benjaminrich/table1")
```

**Comment by samuelsaari** [comment]
With remotes, it seems to work. Version was updated to table1_1.4.3.

Will try with my real code tomorrow and close this if it works.

**Comment by samuelsaari** [comment]
It is indeed working.

In case anyone later stumbles upon this, combining info from the vignette and other issues related to formatting and rounding, this is what I used:

```
my.render.cont <- function (x, ...) {
  with(lapply(stats.default(x, digits=2,digits.pct=1,round.median.min.max = F,round.integers = F),
              round_pad, ...),
       c("",
      `Mean (SD)`         = sprintf("%s (%s)", MEAN, SD)))
}



my.render.cat <- function(x) {
  c("", sapply(stats.default(x,round.median.min.max = F,round.integers = F),
               function(y) with(y, sprintf("%d (%0.1f %%)", FREQ, PCT))))
}
```

That way both continuos and categorical variables are displayed with two decimal spaces, but integers are shown as is—or that is the what I intended anyway.
