### ISSUE TITLE
How do I remove the N=3 below the “stratification” variable?

### ISSUE THREAD

**Issue by crazyxiaoj** [benjaminrich/table1#83]
Dear developer of table1 package, 

If you have time, could you look at this for me? Is there any way to remove the items in the red box?

![image](https://user-images.githubusercontent.com/50630515/172876551-2d09d83f-da5f-416d-a427-5e4bfb48186c.png)

**Comment by benjaminrich** [comment]
You can do so by using the following `render.strat` function:
```r
render.strat <- function(label, ...) {
    sprintf("<span class='stratlabel'>%s</span>", label)
}
```

Here is an example:
```r
library(table1)

set.seed(123)

n <- 12

dat <- data.frame(
    a = rlnorm(n, 1, 1),
    b = rlnorm(n, 1, 1),
    c = rlnorm(n, 1, 1),
    d = rep(LETTERS[1:4], each=3)
)

table1(~ a + b + c | d, data=dat, transpose=T, overall=F,
    render="Mean &pm; SD", render.strat=render.strat)
```
![image](https://user-images.githubusercontent.com/17572252/172879215-418fff62-9481-4297-9cea-db966feea314.png)

**Comment by crazyxiaoj** [comment]
It's works! Thank you for your help!
