### ISSUE TITLE
p value for multiple logistic regression model

### ISSUE THREAD

**Issue by tianfeiwei** [benjaminrich/table1#87]
Hi Benjamin, thanks a lot for making such a great package. It's extremely handy.
I was trying to make my own tweaks of p-value function for logistic regression model, but the final p-value seems not match with my manually calculated p-values. Could you please guide me on this?

```
pvaluetemp <- function(x, ...) {
    x <- x[-length(x)]  # Remove "overall" group
    y <- unlist(x)
    g <- factor(rep(1:length(x), times=sapply(x, length)))
    # p <- kruskal.test(y ~ g)$p.value
    p <- summary(glm(g ~ y+disp + hp + drat,data=mtcars,family = binomial(link = "logit")))$coef[2,4]
    c("", sub("<", "<", format.pval(p, digits=3, eps=0.001)))
}

mtcars$wtf <- ifelse(mtcars$wt > 3, 1, 0)
table1(~ mpg | wtf, data = mtcars, extra.col=list(`P-value`=pvaluetemp), extra.col.pos = c(3))
```
![image](https://user-images.githubusercontent.com/16997565/177890928-c3178624-0044-47fb-9d31-39d200df41ff.png)

but `summary(glm(wtf ~ mpg+disp + hp + drat,data=mtcars,family = binomial(link = "logit")))$coef[2,4]` gives me 0.7562281.

Not sure what did I do wrong? Or is there any alternative ways to just manually input values as `extra.custom.col=list(`P-value`=c(0.756))`? Thanks

**Comment by benjaminrich** [comment]
I see the problem, but I don't quite understand the example (seems a little strange to me). You can get what you want by sorting the `mtcars` data first, like this:

```r
mtcars$wtf <- ifelse(mtcars$wt > 3, 1, 0)
mtcars <- mtcars[order(mtcars$wtf),]

table1(~ mpg | wtf, data = mtcars, extra.col=list(`P-value`=pvaluetemp), extra.col.pos = c(3))
```

![image](https://user-images.githubusercontent.com/17572252/178297734-bd9f3b6e-1034-45c7-bd46-60c625ea2a73.png)

**Comment by tianfeiwei** [comment]
Thank you, this helps a lot!
