### ISSUE TITLE
Suppress percent missing but keep count for missing values using Table1 package?

### ISSUE THREAD

**Issue by EpiPenny** [benjaminrich/table1#89]
Hi,

Thank you for creating this beautiful package!  

I would like to include missing value counts in the table, but not include a percent for the missing values.  I tried using the PCTnoNA option. 

Here is a partial table that shows what I mean:

![image](https://user-images.githubusercontent.com/109321827/179631579-1fe03ebd-af09-4365-8e16-a981a0a33999.png)

I am new to R, but I have tried to find the answer to my problem online, and I have tried to solve it myself without success.  At this point, I am hoping you can help me.

Here is the code I started with:

```{r table1_attempt1}
table1(~ earlycare_f + mage5yr_f + mraceeth_f + smoke_f | 
                   preterm_f, 
                 data=birthsfin, 
                 overall="All",
                 render.categorical="Freq (PCTnoNA%)",  
                 big.mark=","  
)
```
This calculated the percents correctly for the non-missing values.  However, it includes the percent NA out of the total (see blue highlighting in table below). 
 
A second side effect of this code is that it now includes 3 significant figures for non-missing values where the calculated percent is less than 1 instead of only including one decimal place (see yellow highlighting in table below).  

![image](https://user-images.githubusercontent.com/109321827/179631697-a2835197-479b-46c8-a691-63c96e075800.png)

I have been unable to figure out how to get rid of the percents highlighted in blue.  I am hoping you can help me with that.  

In addition, I have been unable to figure out how to use PCTnoNA, _and_ round the percents to the correct number of decimal places, _and_ keep the comma separator at the thousands place.

I tried address this using the following code:

```{r table1_attempt2}
render.cat <- function(x) {
  	c("", sapply(stats.default(x), 
               function(y) with(y,sprintf("%d (%0.1f %%)", FREQ, PCTnoNA))))
}

table1(~ earlycare_f + mage5yr_f + mraceeth_f + smoke_f | 
        preterm_f, 
        data=birthsfin, 
        overall="All",
        render.categorical=render.cat
        #big.mark=","  #Does not work with render.cat
        )
```

This fixed my percent problem (i.e. all percent were rounded to one decimal place), but I lost the comma at the thousands because big mark within the table1 call did not work anymore.

Then I tried the following code (adapted from issue #34)

```{r table1_attempt3}
render.strat <- function (label, n, ...) {
  	sprintf("<span class='stratlabel'>%s<br><span class='stratn'>(N=%s)</span></span>",
          		label, prettyNum(n, big.mark=","))
}

render.categorical <- function(x, ...) {
  	c("", sapply(stats.apply.rounding(stats.default(x)), function(y) 
    		with(y,sprintf("%s (%s%%)", prettyNum(FREQ, big.mark=","), PCTnoNA))))
}

table1(~ earlycare_f + mage5yr_f + mraceeth_f + smoke_f | 
                   preterm_f, 
                 data=birthsfin, 
                 overall="All",
                 render.categorical = render.categorical,
                 render.strat = render.strat
)
```

This code, resulted in comma separators throughout the table, _except_ for the count for the missing values for smoking.  It also reverted back to the same rounding issue as is highlighted in yellow above.  

At this point, I’m not optimistic that I can solve my formatting issues on my own or that I can achieve my original goal of deleting the percent for the missing values.  I would appreciate any help you can offer.  

Thanks!

**Comment by benjaminrich** [comment]
Hi @EpiPenny,

Thanks for the detailed message, and sorry for the long delay. First, the issue with the rounding (yellow highlighting in your post above) should have been fixed in be5e0f73, which is not yet in the version on CRAN, but will be in the next release (which should be happening soon).

For the other issue, please try adding `render.missing="Freq"`. I.e., the whole thing would look like this:

```r
table1(~ earlycare_f + mage5yr_f + mraceeth_f + smoke_f | 
                 preterm_f, 
                 data=birthsfin, 
                 overall="All",
                 render.categorical="Freq (PCTnoNA%)",  
                 render.missing="Freq",  
                 big.mark=","  
```

Please try it and let me know if it works. Thanks.

**Comment by EpiPenny** [comment]
Hi,

Thanks so much for getting back to me about this.  I look forward to the pending update.

In the meantime, I did try the code below, but for some reason, it does not print the missing values at all. Instead for variables that have missing values, it prints the counts and percents for the non-missing levels first, and then it prints the counts only for the non-missing values.  (It also adds a row with an x).  See yellow highlighting in the table below.

Any thoughts about why this is happening?

Thanks,
Penny

#Table 1
table1(~ earlycare_f + mage5yr_fa + mraceeth_f + smoke_f |
         preterm_f,
       data = birthsfin,
       overall = "All Births",
       render.categorical = "Freq (PCTnoNA%)",
       render.missing = "Freq",
       big.mark = ",",
       caption = "<b>Table 1. Characteristics of a Cohort of U.S., Singleton, Live Births by Preterm Birth Status Based on the 2006 U.S. Birth Certificate Data\u{1D43}</b>",
       footnote = c("\u{1D43}Only births reported on the 2003 revised U.S. Standard Birth Certificate were eligible",
                    "\u{1D47}Preterm birth includes live births that occurred at gestational ages 21-36 weeks inclusive")
)



Table 1. Characteristics of a Cohort of U.S., Singleton, Live Births by Preterm Birth Status Based on the 2006 U.S. Birth Certificate Dataᵃ

All Births
(N=55,711)
Term
(N=49,402)
Pretermᵇ
(N=6,309)
Entry into prenatal care



  Not Early
10,177 (18.3%)
8,866 (17.9%)
1,311 (20.8%)
  Early
45,534 (81.7%)
40,536 (82.1%)
4,998 (79.2%)
Maternal age (years)



  12-14
97 (0.174%)
77 (0.156%)
20 (0.317%)
  15-19
6,024 (10.8%)
5,134 (10.4%)
890 (14.1%)
  20-24
15,004 (26.9%)
13,291 (26.9%)
1,713 (27.2%)
  25-29
15,534 (27.9%)
13,941 (28.2%)
1,593 (25.2%)
  30-34
11,825 (21.2%)
10,588 (21.4%)
1,237 (19.6%)
  35-39
5,952 (10.7%)
5,282 (10.7%)
670 (10.6%)
  40-44
1,218 (2.19%)
1,045 (2.12%)
173 (2.74%)
  >=45
57 (0.102%)
44 (0.0891%)
13 (0.206%)
Maternal.race.ethnicity



  White
31,938 (57.5%)
28,770 (58.4%)
3,168 (50.5%)
  African.American
7,314 (13.2%)
6,143 (12.5%)
1,171 (18.7%)
  American.Indian.Alaska.Native
332 (0.598%)
282 (0.573%)
50 (0.797%)
  Asian
1,737 (3.13%)
1,573 (3.20%)
164 (2.61%)
  Hawaiian.Pacific.Islander
60 (0.108%)
54 (0.110%)
6 (0.0956%)
  Hispanic
13,512 (24.3%)
11,880 (24.1%)
1,632 (26.0%)
  Multi.racial
612 (1.10%)
528 (1.07%)
84 (1.34%)
  X



  White.1
31,938
28,770
3,168
  African.American.1
7,314
6,143
1,171
  American.Indian.Alaska.Native.1
332
282
50
  Asian.1
1,737
1,573
164
  Hawaiian.Pacific.Islander.1
60
54
6
  Hispanic.1
13,512
11,880
1,632
  Multi.racial.1
612
528
84
Smoked.during.pregnancy



  No
40,702 (86.9%)
36,292 (87.3%)
4,410 (84.1%)
  Yes
6,124 (13.1%)
5,293 (12.7%)
831 (15.9%)
  X



  No.1
40,702
36,292
4,410
  Yes.1
6,124
5,293
831
ᵃOnly births reported on the 2003 revised U.S. Standard Birth Certificate were eligible
ᵇPreterm birth includes live births that occurred at gestational ages 21-36 weeks inclusive



From: Benjamin Rich ***@***.***>
Sent: Monday, January 2, 2023 1:26 PM
To: benjaminrich/table1 ***@***.***>
Cc: Howards, Penelope ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [benjaminrich/table1] Suppress percent missing but keep count for missing values using Table1 package? (Issue #89)


Hi @EpiPenny<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FEpiPenny&data=05%7C01%7Cphoward%40emory.edu%7C3e50190739024dcc210808daeceec4d7%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C638082807520135398%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=4cAlQEuI3wQ%2FjnsReJBAKcPsFqsCTR%2FM6G25jaYXwN8%3D&reserved=0>,

Thanks for the detailed message, and sorry for the long delay. First, the issue with the rounding (yellow highlighting in your post above) should have been fixed in be5e0f7<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbenjaminrich%2Ftable1%2Fcommit%2Fbe5e0f73b59c58e4b65bd1e31ce4481ab0af98d7&data=05%7C01%7Cphoward%40emory.edu%7C3e50190739024dcc210808daeceec4d7%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C638082807520135398%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=6WA%2BL3M%2BBaKJsEJ8qgcirRou4sITrosruYLsSlvMv6Q%3D&reserved=0>, which is not yet in the version on CRAN, but will be in the next release (which should be happening soon).

For the other issue, please try adding render.missing="Freq". I.e., the whole thing would look like this:

table1(~ earlycare_f + mage5yr_f + mraceeth_f + smoke_f |

                 preterm_f,

                 data=birthsfin,

                 overall="All",

                 render.categorical="Freq (PCTnoNA%)",

                 render.missing="Freq",

                 big.mark=","

Please try it and let me know if it works. Thanks.

**Comment by EpiPenny** [comment]
Hi, 

Thanks so much for getting back to me about this.  I look forward to the pending update.  

In the meantime, I did try the code below, but for some reason, it does not print the missing values at all. Instead for variables that have missing values, it prints the counts and percents for the non-missing levels first, and then it prints the counts only for the non-missing values.  (It also adds a row with an x).  See yellow highlighting in the table below.

Any thoughts about why this is happening?

Thanks!

```
#Table 1 code
table1(~ earlycare_f + mage5yr_fa + mraceeth_f + smoke_f | 
         preterm_f, 
       data = birthsfin, 
       overall = "All Births",
       render.categorical = "Freq (PCTnoNA%)", 
       render.missing = "Freq",
       big.mark = ",",
       caption = "<b>Table 1. Characteristics of a Cohort of U.S., Singleton, Live Births by Preterm Birth Status Based on the 2006 U.S. Birth Certificate Data\u{1D43}</b>",
       footnote = c("\u{1D43}Only births reported on the 2003 revised U.S. Standard Birth Certificate were eligible",
                    "\u{1D47}Preterm birth includes live births that occurred at gestational ages 21-36 weeks inclusive")
)
```
![image](https://user-images.githubusercontent.com/109321827/210281938-60f0030e-b959-4b34-8ba8-1c27bc9a75da.png)

**Comment by benjaminrich** [comment]
Please install the latest "development" version using the remotes package:

```r
remotes::install_github("benjaminrich/table1")
```

Then try again and let me know if you are still having the same issue. Thanks.

**Comment by benjaminrich** [comment]
Hi @EpiPenny,

I think this is fixed now in the new version 1.4.3 that just appeared on CRAN. Can you please try updating and let me know?

Thanks

**Comment by EpiPenny** [comment]
Hi,

I tried it, and the resulting table was exactly what I wanted.  

Thank you so much for addressing this!!!

**Comment by benjaminrich** [comment]
Great! I'm just sorry it took so long. Thanks for your patience and for helping to improve the package.
