### ISSUE TITLE
Add significance as logical option

### ISSUE THREAD

**Issue by g-antonello** [benjaminrich/table1#90]
Dear Benjamin, 
Thank you for this tool, tables look great. I have a little request following up on https://cran.r-project.org/web/packages/table1/vignettes/table1-examples.html#example-a-column-of-p-values. Wouldn't it be useful for people to have an easy and quick option (TRUE/FALSE) in the `table1` function to add a p-value? something like `pvalue.column = TRUE` that would do:
- wilcoxon test for `2-category vs continuous` 
- kruskal.test for `n-category vs continuous `
- Fisher exact test for `2-category vs 2-category` 
- chi.squared for `n-category vs k-category`

Multiple testing could be taken into account too. 

This way people could have a rough idea and possibly copy-paste the table as a real demographic table 1. 

Best
Giacomo

**Comment by benjaminrich** [comment]
Hi Giacomo,

I appreciate the suggestion, but I prefer not to make such decisions for the user. This has always been my position, to keep the package flexible and give the user the possibility of doing what they want rather than making the decision for them, as I believe this is too subjective.
