### ISSUE TITLE
Percent of overall in column headers

### ISSUE THREAD

**Issue by eyer** [benjaminrich/table1#92]
Is there a way to add the percent of overall in the column headers? Something like

Hyper
(N=100, 10%)

Normal
(N=900, 90%)

Overall
(N=1000, 100%)

**Comment by benjaminrich** [comment]
It is possible. Here is an example:

```r
dat <- data.frame(x=1, y=rep(c("Hyper", "Normal"), times=c(100, 900)))

render.strat <- function(label, n, transpose=F) {
    total <- sum(as.numeric(n[names(label) != "overall"]))
    pct <- 100*as.numeric(n)/total
    sprintf(
        ifelse(is.na(n), 
            "<span class='stratlabel'>%s</span>",
            "<span class='stratlabel'>%s<br><span class='stratn'>(N=%s, %s%%)</span></span>"),
        label, n, round(pct, 1))
}

table1(~ x | y, data=dat, render.strat=render.strat)
```
![image](https://user-images.githubusercontent.com/17572252/204883978-521f6fa0-d1c0-45be-8b12-178e0254e204.png)

**Comment by samuelsaari** [comment]
The percentage information seems to be lost when I try to convert this to LaTeX via Kable:

(table1 <- table1(~ x | y, data=dat, render.strat=render.strat))

t1kable(table1,format='latex')

**Comment by samuelsaari** [comment]
Thank you. I am aware that it is already hacky, but is there any chance that N and % could be divided to to different lines. I get close but do not know how to modify the "N=".

![image](https://github.com/benjaminrich/table1/assets/49607659/42489a3b-f636-474f-a914-78e815cdd37f)
