### ISSUE TITLE
Remove "Missing" row for select categorical variables

### ISSUE THREAD

**Issue by chitrams** [benjaminrich/table1#94]
I'd like to remove the "Missing" rows from the following table for the variables `alcgp` and `tobgp` only, and subsequently exclude the missing values from the percentage calculation for these variables.

![Screenshot 2022-11-23 090700](https://user-images.githubusercontent.com/13806861/203451258-ba07853d-4a89-4cab-8d52-f076c18e640d.png)

I used the `esoph` data from `datasets` and randomly added missing values. Here's the data and code:

```R
d <- esoph

# Randomly add missing values in data
set.seed(35)
d <- as.data.frame(lapply(d, function(cc) cc[ sample(c(TRUE, NA), prob = c(0.85, 0.15), size = length(cc), replace = TRUE) ]))

# Create table
table1(~ agegp + alcgp + tobgp, data = d)
```
I'm aware I can use the options `render.missing = NULL` and `render.categorical = "FREQ (PCTnoNA%)"` (thanks to issue #21!), but this removes missing the "Missing" row for all three variables. If there's a way to select which one (or more) variable(s) I can remove the "Missing" row for, that would be great.

Thank you!

**Comment by benjaminrich** [comment]
It is possible, using the following custom render function:

```r
rndr <- function(x, name, ...) {
    if (name %in% c("alcgp", "tobgp")) {
        render.default(x, name, render.missing=NULL, render.categorical = "FREQ (PCTnoNA%)", ...)
    } else {
        render.default(x, name, ...)
    }
}

# Create table
table1(~ agegp + alcgp + tobgp, data = d, render=rndr)
```
![image](https://user-images.githubusercontent.com/17572252/204881528-fc045472-4a1f-4394-8f9b-6f741a32235a.png)

**Comment by chitrams** [comment]
Thank you so much! This custom render function is exactly what I'm looking for. 

The reprex I used here isn't the best example for what this feature would be used for. This feature is useful in instances where, for example, the variables are "Number of cases" and "Number of tobacco use for cases" in the one table. The missing values for "Number of tobacco use for cases" would be irrelevant as this is the number of non-cases (which would be shown in the "Number of cases" variable).

Would this custom render function be worth integrating into future versions of the table1 function?

Thank you again for your help, I really appreciate it. Great work on this package--it's my favourite for creating tables.
