### ISSUE TITLE
Group variables under a heading

### ISSUE THREAD

**Issue by richardjohnmooney** [benjaminrich/table1#98]
Good morning,

Excellent package, tables looks great.

I'd like to create a table1 style that I've seen in JAMA - where the presence or absence of chronic diseases is grouped under a heading "Chronic Disease", with the disease in question (e.g. COPD, IHD) represented as a variable beneath?

Is this possible? A solution I considered was to include the disease present as a factor under the column "chronicdisease" in a df, but then we have the obvious issue that a participant with two diseases will be improperly represented.

**Comment by benjaminrich** [comment]
Indeed, I've seen this type of output in journals and it is nice and compact. I can offer a solution using a custom render function (which might be considered a bit hackish - it would be nice if there were a built-in feature to make this easier):

```r
library(table1)

# Simulate data
set.seed(123)

n <- 234
dat <- data.frame(id=1:n, group=sample(LETTERS[1:2], n, replace=T))

dat$COPD <- as.logical(rbinom(n, 1, 0.3))
dat$IHD  <- as.logical(rbinom(n, 1, 0.4))



# Create a 'dummy' variable
dat$disease <- 1:nrow(dat)
label(dat$disease) <- "Chronic Disease, n (%)"

rndr <- function(x, name, ...) {
    if (name=="disease") {
        vars <- c("COPD", "IHD")
        y <- sapply(vars, function(var) {
            render.default(dat[[var]][x])[2]
        })
        names(y) <- sapply(vars, function(var) {
            l <- label(dat$var)
            if (is.null(l)) var else l
        })
        c("", y)
    }
}

table1(~ disease | group, data=dat, render=rndr)
```
![image](https://user-images.githubusercontent.com/17572252/221420268-f6b3c353-3029-4e64-9591-d7e4e0eaed8c.png)

**Comment by richardjohnmooney** [comment]
That's fantastic - thank you so much.


I've run into one issue (and I really should be able to fix this myself I'm sure, but my coding isn't the best):
It looks like the labels for my individual disease columns (COPD, IHD) are stripped by this function, hence your `"if (is.null(l)) var else l"`. 
A lot of my diseases have spaces in them - for example, "Chronic Respiratory Disease". Is there a way to get the labels working?

![Screenshot 2023-02-27 023252](https://user-images.githubusercontent.com/77871181/221429626-db9da2f0-335c-4051-81f4-87c3d4195440.png)


Your answer is incredibly helpful, and I'd be happy to close the issue if this is too hard - I can always manually edit the html table at the end to get the variable names looking nicer.

**Comment by benjaminrich** [comment]
Here is an updated render function that should pick up those labels:

```r
rndr <- function(x, name, ...) {
    if (name=="disease") {
        d <- dat[x, c("COPD", "IHD", "chronicresp")]
        l <- lapply(dat, label)[names(d)]
        names(d)[!sapply(l, is.null)] <- l[!sapply(l, is.null)]
        c("", sapply(d, render.default)[2,, drop=T])
    } else {
        render.default(x, name, ...)
    }
}
```

**Comment by richardjohnmooney** [comment]
Fabulous - very grateful for your time

![Screenshot 2023-02-27 092207](https://user-images.githubusercontent.com/77871181/221451103-55f0cdfb-fe18-48eb-a821-82a535988082.png)
